//! The catalogue compiler (A3.6), behind feature `compile`; `kd catalog`, `kd-tools` at start and `kd-app`'s build
//! script run it. It takes the files' texts from its caller and reads no file itself: every `data/**/*.md` in sorted
//! path order is split at its `##` headings, each entry's one `toml` block parsed into its kind's schema with no
//! unknown or missing field, its id resolved to its number in `data/ids.lock`, and the entries put in number order
//! and encoded as the blob. Rules 1, 2, 4 and 6 of A3.6's validation hold for the kinds so far.
//!
//! Implements MAT-17, see A3.6: every entry names its checks, and an entry that breaks a rule fails with its file
//! and line.

use core::fmt;
use std::collections::BTreeMap;

use serde::Deserialize;
use serde::de::DeserializeOwned;

use crate::blob;
use crate::kinds::{FileRole, Kind, role};
use crate::schema::{Air, Catalogue, Colour, Look, Versions};

pub const VERSION_FILE: &str = "data/VERSION.toml";
pub const LOCK_FILE: &str = "data/ids.lock";
pub const INDEX_FILE: &str = "data/INDEX.md";
pub const TABLE_START: &str = "<!-- table: generated by `kd catalog tables`; edit the block, not the table -->";
pub const TABLE_END: &str = "<!-- end table -->";

/// A file under `data/`: its path from the repository's root, with `/` between parts, and its text.
#[derive(Clone, Debug)]
pub struct Source {
    pub path: String,
    pub text: String,
}

/// A problem, where it is.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Problem {
    pub path: String,
    pub line: usize,
    pub message: String,
}

impl fmt::Display for Problem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}:{}: {}", self.path, self.line, self.message)
    }
}

/// What compiling gives.
#[derive(Clone, Debug)]
pub struct Output {
    pub catalogue: Catalogue,
    pub blob: Vec<u8>,
    /// `data/ids.lock` as it now reads: with `assign`, new entries have their numbers.
    pub lock: String,
    /// Each file whose generated parts (the entries' tables, the index) differ from what the blocks give, with its
    /// text made afresh; `kd catalog tables` writes them, and `kd catalog check` fails while any is listed.
    pub stale: Vec<(String, String)>,
    pub entries: usize,
}

/// One entry as written: its heading, its line, its block and the lines its table and block hold.
struct Entry {
    path: String,
    heading: String,
    line: usize,
    block: String,
    block_line: usize,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ColourSrc {
    id: String,
    name: String,
    stage: String,
    checks: Vec<String>,
    value: String,
    #[serde(rename = "use")]
    use_: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct LookSrc {
    id: String,
    name: String,
    stage: String,
    checks: Vec<String>,
    colour: String,
    steps: u8,
    sheen: Option<f32>,
    glow: Option<String>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct AirSrc {
    id: String,
    name: String,
    stage: String,
    checks: Vec<String>,
    wavelengths_nm: [f32; 3],
    rayleigh: [f32; 3],
    turbidity: f32,
    aerosol_exponent: f32,
    ozone: [f32; 3],
    sky_rayleigh_share: f32,
    sky_aerosol_share: f32,
    horizon_sky: f32,
    horizon_fade_deg: f32,
    twilight_end_deg: f32,
    twilight_fall_deg: f32,
    twilight_ozone_per_deg: f32,
    moon_weakness: f32,
    moon_tint: [f32; 3],
    starlight: f32,
    exposure_scale: f32,
    exposure_power: f32,
    rods_start: f32,
    rods_full: f32,
    grade_chroma: f32,
    haze_levels: [f32; 3],
    haze_mixes: [f32; 3],
    haze_g: f32,
    aerosol_height_m: f32,
    rayleigh_height_m: f32,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct VersionSrc {
    major: u16,
    minor: u16,
    generator: u16,
}

/// The numbers of one kind in `data/ids.lock`: live ids and retired ones.
#[derive(Clone, Debug, Default)]
struct KindLock {
    live: BTreeMap<String, u16>,
    retired: BTreeMap<String, u16>,
}

impl KindLock {
    fn next(&self) -> u16 {
        self.live
            .values()
            .chain(self.retired.values())
            .map(|&n| n + 1)
            .max()
            .unwrap_or(0)
    }
}

/// Compiles the sources: `assign` gives new entries their numbers. Hard problems fail; stale generated parts come
/// back in `Output::stale`.
pub fn compile(sources: &[Source], assign: bool) -> Result<Output, Vec<Problem>> {
    let mut problems = Vec::new();
    let mut sorted: Vec<&Source> = sources.iter().collect();
    sorted.sort_by(|a, b| a.path.cmp(&b.path));
    let find = |path: &str| sorted.iter().find(|s| s.path == path).map(|s| s.text.as_str());

    let versions = match find(VERSION_FILE).map(toml::from_str::<VersionSrc>) {
        Some(Ok(v)) => Versions {
            major: v.major,
            minor: v.minor,
            generator: v.generator,
        },
        Some(Err(e)) => {
            problems.push(at(VERSION_FILE, 1, e.message().to_string()));
            Versions::default()
        }
        None => {
            problems.push(at(
                VERSION_FILE,
                1,
                "missing: it holds major, minor and generator (A3.6)".into(),
            ));
            Versions::default()
        }
    };
    let mut locks = parse_lock(find(LOCK_FILE).unwrap_or(""), &mut problems);

    // Every entries file, split into entries.
    let mut by_kind: BTreeMap<Kind, Vec<Entry>> = BTreeMap::new();
    let mut files: Vec<(&Source, Kind)> = Vec::new();
    for s in &sorted {
        if !s.path.ends_with(".md") {
            continue;
        }
        match role(&s.path) {
            FileRole::Entries(kind) => {
                files.push((s, kind));
                by_kind.entry(kind).or_default().extend(entries(s, &mut problems));
            }
            FileRole::Unclaimed => problems.push(at(&s.path, 1, "no kind of entry claims this file (A3.6)".into())),
            FileRole::Other => {}
        }
    }

    // Each kind's entries parsed, checked, numbered and compiled.
    let mut colours: Vec<(u16, Colour)> = Vec::new();
    let mut looks: Vec<(u16, Look)> = Vec::new();
    let mut airs: Vec<(u16, Air)> = Vec::new();
    let mut tables: BTreeMap<String, Vec<(usize, String)>> = BTreeMap::new();
    let mut index: BTreeMap<Kind, Vec<(u16, String, String, String)>> = BTreeMap::new();
    let mut count = 0;
    for kind in Kind::ALL {
        let lock = locks.entry(kind.name().to_string()).or_default();
        let mut seen: BTreeMap<String, usize> = BTreeMap::new();
        for e in by_kind.remove(&kind).unwrap_or_default() {
            count += 1;
            let compiled = match kind {
                Kind::Colour => parse::<ColourSrc>(&e, &mut problems).map(|s| {
                    let head = head(&s.id, &s.name, &s.stage, &s.checks);
                    let rgb = colour(&s.value).unwrap_or_else(|| {
                        problems.push(at(&e.path, e.block_line, format!("value {:?} is not #rrggbb", s.value)));
                        [0; 3]
                    });
                    if s.use_.trim().is_empty() {
                        problems.push(at(
                            &e.path,
                            e.block_line,
                            "a fixed colour says what it is used for".into(),
                        ));
                    }
                    let table = vec![
                        ("Value".to_string(), hex(rgb)),
                        ("Use".to_string(), s.use_.trim().to_string()),
                    ];
                    (
                        head,
                        table,
                        Compiled::Colour(Colour {
                            id: s.id.clone(),
                            name: s.name.clone(),
                            number: 0,
                            rgb,
                        }),
                    )
                }),
                Kind::Look => parse::<LookSrc>(&e, &mut problems).map(|s| {
                    let head = head(&s.id, &s.name, &s.stage, &s.checks);
                    let rgb = colour(&s.colour).unwrap_or_else(|| {
                        problems.push(at(
                            &e.path,
                            e.block_line,
                            format!("colour {:?} is not #rrggbb", s.colour),
                        ));
                        [0; 3]
                    });
                    if !(4..=7).contains(&s.steps) {
                        problems.push(at(
                            &e.path,
                            e.block_line,
                            format!("{} steps: a look has 4 to 7 (PRE-20)", s.steps),
                        ));
                    }
                    let sheen = s.sheen.unwrap_or(0.0);
                    if !(0.0..=1.0).contains(&sheen) {
                        problems.push(at(&e.path, e.block_line, format!("sheen {sheen} is outside 0–1")));
                    }
                    let glow = s.glow.as_deref().map(|g| {
                        colour(g).unwrap_or_else(|| {
                            problems.push(at(&e.path, e.block_line, format!("glow {g:?} is not #rrggbb")));
                            [0; 3]
                        })
                    });
                    let table = vec![
                        ("Colour under white light".to_string(), hex(rgb)),
                        ("Steps".to_string(), s.steps.to_string()),
                        (
                            "Sheen".to_string(),
                            if sheen > 0.0 { sheen.to_string() } else { "none".into() },
                        ),
                        ("Glow".to_string(), glow.map(hex).unwrap_or_else(|| "none".into())),
                    ];
                    let entry = Look {
                        id: s.id.clone(),
                        name: s.name.clone(),
                        number: 0,
                        rgb,
                        steps: s.steps,
                        sheen,
                        glow,
                    };
                    (head, table, Compiled::Look(entry))
                }),
                Kind::Light => parse::<AirSrc>(&e, &mut problems).map(|s| {
                    check_air(&s, &e, &mut problems);
                    (
                        head(&s.id, &s.name, &s.stage, &s.checks),
                        air_table(&s),
                        Compiled::Air(air_of(&s)),
                    )
                }),
            };
            let Some((head, table, entry)) = compiled else { continue };
            // Rules 2 and 6: the id, the name, the stage and the checks.
            check_head(&head, &e, &mut problems);
            if let Some(first) = seen.insert(head.id.clone(), e.line) {
                problems.push(at(
                    &e.path,
                    e.line,
                    format!("id {} is used twice (first on line {first})", head.id),
                ));
                continue;
            }
            let number = if let Some(&n) = lock.live.get(&head.id) {
                n
            } else if lock.retired.contains_key(&head.id) {
                problems.push(at(
                    &e.path,
                    e.line,
                    format!("id {} is retired and may not come back", head.id),
                ));
                continue;
            } else if assign {
                let n = lock.next();
                lock.live.insert(head.id.clone(), n);
                n
            } else {
                problems.push(at(
                    &e.path,
                    e.line,
                    format!("id {} has no number: kd catalog build --assign", head.id),
                ));
                continue;
            };
            tables
                .entry(e.path.clone())
                .or_default()
                .push((e.line, table_text(&table)));
            index
                .entry(kind)
                .or_default()
                .push((number, head.id.clone(), head.name.clone(), head.stage.clone()));
            match entry {
                Compiled::Colour(c) => colours.push((number, Colour { number, ..c })),
                Compiled::Look(l) => looks.push((number, Look { number, ..l })),
                Compiled::Air(a) => airs.push((number, a)),
            }
        }
    }

    // Kind-wide rules: there is exactly one air, and the palette holds every colour. That fixed colour 0 is void,
    // palette index 0, the renderer's tests check, since rules here never name an entry (A2.3 rule 5).
    colours.sort_by_key(|c| c.0);
    looks.sort_by_key(|l| l.0);
    if airs.len() != 1 {
        problems.push(at(
            Kind::Light.place(),
            1,
            format!("{} entries of air; there is exactly one (A11.4)", airs.len()),
        ));
    }
    if colours.len() + looks.len() > 256 {
        problems.push(at(
            Kind::Look.place(),
            1,
            "more than 255 colours besides void (A11.3)".into(),
        ));
    }
    if !problems.is_empty() {
        return Err(problems);
    }

    let catalogue = Catalogue {
        versions,
        colours: colours.into_iter().map(|c| c.1).collect(),
        looks: looks.into_iter().map(|l| l.1).collect(),
        air: airs.remove(0).1,
    };
    let mut stale = Vec::new();
    for (s, _) in &files {
        let fresh = with_tables(&s.text, tables.get(&s.path).map(Vec::as_slice).unwrap_or(&[]));
        if fresh != s.text {
            stale.push((s.path.clone(), fresh));
        }
    }
    let fresh_index = index_text(&index);
    if find(INDEX_FILE) != Some(fresh_index.as_str()) {
        stale.push((INDEX_FILE.to_string(), fresh_index));
    }
    Ok(Output {
        blob: blob::encode(&catalogue),
        catalogue,
        lock: lock_text(&locks),
        stale,
        entries: count,
    })
}

enum Compiled {
    Colour(Colour),
    Look(Look),
    Air(Air),
}

/// The fields every entry has (A3.6).
struct Head {
    id: String,
    name: String,
    stage: String,
    checks: Vec<String>,
}

fn head(id: &str, name: &str, stage: &str, checks: &[String]) -> Head {
    Head {
        id: id.into(),
        name: name.into(),
        stage: stage.into(),
        checks: checks.to_vec(),
    }
}

fn at(path: &str, line: usize, message: String) -> Problem {
    Problem {
        path: path.to_string(),
        line,
        message,
    }
}

/// A file's entries: its `##` headings, each with exactly one `toml` block (rule 1); the file opens with a `#` title.
fn entries(s: &Source, problems: &mut Vec<Problem>) -> Vec<Entry> {
    let lines: Vec<&str> = s.text.lines().collect();
    if !lines
        .iter()
        .find(|l| !l.trim().is_empty())
        .is_some_and(|l| l.starts_with("# "))
    {
        problems.push(at(
            &s.path,
            1,
            "a catalogue file opens with a # title and a short introduction".into(),
        ));
    }
    let mut out = Vec::new();
    let heads: Vec<usize> = (0..lines.len()).filter(|&i| lines[i].starts_with("## ")).collect();
    for (k, &h) in heads.iter().enumerate() {
        let end = heads.get(k + 1).copied().unwrap_or(lines.len());
        let mut blocks = Vec::new();
        let mut i = h + 1;
        while i < end {
            if lines[i].trim_end() == "```toml" {
                let start = i + 1;
                let mut j = start;
                while j < end && lines[j].trim_end() != "```" {
                    j += 1;
                }
                blocks.push((start, lines[start..j.min(end)].join("\n")));
                i = j + 1;
            } else {
                i += 1;
            }
        }
        let heading = lines[h][3..].trim().to_string();
        match blocks.len() {
            1 => {
                let (start, block) = blocks.remove(0);
                out.push(Entry {
                    path: s.path.clone(),
                    heading,
                    line: h + 1,
                    block,
                    block_line: start + 1,
                });
            }
            n => problems.push(at(
                &s.path,
                h + 1,
                format!("{heading}: {n} toml blocks; an entry has exactly one"),
            )),
        }
    }
    out
}

/// An entry's block in its kind's schema, or the parser's problem at its line (rule 1).
fn parse<T: DeserializeOwned>(e: &Entry, problems: &mut Vec<Problem>) -> Option<T> {
    match toml::from_str::<T>(&e.block) {
        Ok(t) => Some(t),
        Err(err) => {
            let line = err
                .span()
                .map_or(0, |r| e.block[..r.start.min(e.block.len())].matches('\n').count());
            problems.push(at(
                &e.path,
                e.block_line + line,
                format!("{}: {}", e.heading, err.message().trim()),
            ));
            None
        }
    }
}

/// Rule 2 and rule 6: the id is snake_case, the name is the heading, the stage a milestone, and the checks name
/// at least one ID.
fn check_head(h: &Head, e: &Entry, problems: &mut Vec<Problem>) {
    let snake = h.id.chars().next().is_some_and(|c| c.is_ascii_lowercase())
        && h.id
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_');
    if !snake {
        problems.push(at(&e.path, e.line, format!("id {:?} is not snake_case", h.id)));
    }
    if h.name != e.heading {
        problems.push(at(
            &e.path,
            e.line,
            format!("name {:?} is not the heading {:?}", h.name, e.heading),
        ));
    }
    let milestone = h.stage.len() == 6
        && h.stage.starts_with("MIL-0")
        && h.stage[5..].parse::<u8>().is_ok_and(|n| (1..=7).contains(&n));
    if !milestone {
        problems.push(at(
            &e.path,
            e.line,
            format!("stage {:?} is not a milestone, MIL-01 to MIL-07", h.stage),
        ));
    }
    let is_id = |c: &str| {
        let (area, num) = c.split_at(c.find('-').unwrap_or(0));
        area.len() == 3
            && area.chars().all(|x| x.is_ascii_uppercase())
            && (3..=4).contains(&num.len())
            && num[1..].chars().all(|x| x.is_ascii_digit())
    };
    if h.checks.is_empty() {
        problems.push(at(&e.path, e.line, format!("{} names no checks (MAT-17)", h.id)));
    }
    for c in h.checks.iter().filter(|c| !is_id(c)) {
        problems.push(at(&e.path, e.line, format!("checks holds {c:?}, not an ID")));
    }
}

/// `#rrggbb` as three bytes.
fn colour(s: &str) -> Option<[u8; 3]> {
    let hex = s
        .strip_prefix('#')
        .filter(|h| h.len() == 6 && h.chars().all(|c| c.is_ascii_hexdigit()))?;
    let byte = |i: usize| u8::from_str_radix(&hex[i..i + 2], 16).ok();
    Some([byte(0)?, byte(2)?, byte(4)?])
}

fn hex(c: [u8; 3]) -> String {
    format!("#{:02x}{:02x}{:02x}", c[0], c[1], c[2])
}

fn check_air(s: &AirSrc, e: &Entry, problems: &mut Vec<Problem>) {
    let mut bad = |what: &str| problems.push(at(&e.path, e.block_line, format!("air: {what}")));
    if !(0.0..=1.0).contains(&s.turbidity) {
        bad("turbidity outside 0–1");
    }
    if !(s.twilight_end_deg < 0.0 && s.twilight_fall_deg > 0.0) {
        bad("twilight ends below the horizon and falls by e over a positive number of degrees");
    }
    if !(s.rods_full < s.rods_start && s.rods_start < 1.0 && s.rods_full > 0.0) {
        bad("rod vision starts above where it is full, both below noon's light");
    }
    if !(s.haze_levels[0] < s.haze_levels[1] && s.haze_levels[1] < s.haze_levels[2] && s.haze_levels[2] < 1.0) {
        bad("haze levels rise below 1");
    }
    if !(s.haze_mixes.iter().all(|&m| (0.0..=1.0).contains(&m)) && s.haze_mixes[0] < s.haze_mixes[2]) {
        bad("haze mixes lie in 0–1 and rise");
    }
    if !(0.0..1.0).contains(&s.haze_g) || s.grade_chroma < 1.0 || s.exposure_power <= 0.0 || s.moon_weakness <= 1.0 {
        bad("g in 0–1, the grade at least 1, exposure's power and the moon's weakness positive");
    }
}

fn air_of(s: &AirSrc) -> Air {
    Air {
        id: s.id.clone(),
        name: s.name.clone(),
        wavelengths_nm: s.wavelengths_nm,
        rayleigh: s.rayleigh,
        turbidity: s.turbidity,
        aerosol_exponent: s.aerosol_exponent,
        ozone: s.ozone,
        sky_rayleigh_share: s.sky_rayleigh_share,
        sky_aerosol_share: s.sky_aerosol_share,
        horizon_sky: s.horizon_sky,
        horizon_fade_deg: s.horizon_fade_deg,
        twilight_end_deg: s.twilight_end_deg,
        twilight_fall_deg: s.twilight_fall_deg,
        twilight_ozone_per_deg: s.twilight_ozone_per_deg,
        moon_weakness: s.moon_weakness,
        moon_tint: s.moon_tint,
        starlight: s.starlight,
        exposure_scale: s.exposure_scale,
        exposure_power: s.exposure_power,
        rods_start: s.rods_start,
        rods_full: s.rods_full,
        grade_chroma: s.grade_chroma,
        haze_levels: s.haze_levels,
        haze_mixes: s.haze_mixes,
        haze_g: s.haze_g,
        aerosol_height_m: s.aerosol_height_m,
        rayleigh_height_m: s.rayleigh_height_m,
    }
}

fn three(v: [f32; 3]) -> String {
    format!("{}, {}, {}", v[0], v[1], v[2])
}

fn air_table(s: &AirSrc) -> Vec<(String, String)> {
    vec![
        (
            "Channels".into(),
            format!(
                "{}, {} and {} nm",
                s.wavelengths_nm[0], s.wavelengths_nm[1], s.wavelengths_nm[2]
            ),
        ),
        ("Rayleigh depths".into(), three(s.rayleigh)),
        (
            "Aerosol".into(),
            format!("turbidity {}, exponent {}", s.turbidity, s.aerosol_exponent),
        ),
        ("Ozone depths".into(), three(s.ozone)),
        (
            "Sky light".into(),
            format!(
                "Rayleigh's share {}, the aerosol's {}; at sunset {}, fading over {}°",
                s.sky_rayleigh_share, s.sky_aerosol_share, s.horizon_sky, s.horizon_fade_deg
            ),
        ),
        (
            "Twilight, night".into(),
            format!(
                "to {}°, e every {}°, ozone {} air masses a degree; moon 1/{}, tint {}; starlight {}",
                s.twilight_end_deg,
                s.twilight_fall_deg,
                s.twilight_ozone_per_deg,
                s.moon_weakness,
                three(s.moon_tint),
                s.starlight
            ),
        ),
        (
            "Exposure, rods".into(),
            format!(
                "scale {}, power {}; colour fades from {} to {} of noon",
                s.exposure_scale, s.exposure_power, s.rods_start, s.rods_full
            ),
        ),
        (
            "Grade, haze".into(),
            format!(
                "chroma × {}; levels {}; mixes {}; g {}; heights {} and {} m",
                s.grade_chroma,
                three(s.haze_levels),
                three(s.haze_mixes),
                s.haze_g,
                s.aerosol_height_m,
                s.rayleigh_height_m
            ),
        ),
    ]
}

/// An entry's generated table, between its markers.
fn table_text(rows: &[(String, String)]) -> String {
    let mut t = format!("{TABLE_START}\n| | |\n|---|---|\n");
    for (k, v) in rows {
        t.push_str(&format!("| {k} | {} |\n", v.replace('|', "\\|")));
    }
    t.push_str(TABLE_END);
    t
}

/// A file with each entry's table made afresh: the old one replaced, or a new one put before the entry's block.
fn with_tables(text: &str, tables: &[(usize, String)]) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let mut out: Vec<String> = Vec::new();
    let mut i = 0;
    let mut pending: Option<&String> = None;
    while i < lines.len() {
        let line = lines[i];
        if line.starts_with("## ") {
            pending = tables.iter().find(|(l, _)| *l == i + 1).map(|(_, t)| t);
        }
        if line.trim_end() == TABLE_START {
            // Drop the old table up to its end marker; the fresh one goes in its place.
            while i < lines.len() && lines[i].trim_end() != TABLE_END {
                i += 1;
            }
            i += 1;
            if let Some(t) = pending.take() {
                out.extend(t.lines().map(String::from));
            }
            continue;
        }
        if line.trim_end() == "```toml"
            && let Some(t) = pending.take()
        {
            out.extend(t.lines().map(String::from));
            out.push(String::new());
        }
        out.push(line.to_string());
        i += 1;
    }
    let mut s = out.join("\n");
    if text.ends_with('\n') {
        s.push('\n');
    }
    s
}

/// `data/INDEX.md`: one table a kind (A3.6).
fn index_text(index: &BTreeMap<Kind, Vec<(u16, String, String, String)>>) -> String {
    let mut s = String::from(
        "# Catalogue index\n\nGenerated by `kd catalog tables` from the entries' blocks (A3.6); edit the entries, never this file.\n",
    );
    for kind in Kind::ALL {
        let title = match kind {
            Kind::Colour => "Fixed colours",
            Kind::Look => "Looks",
            Kind::Light => "The air",
        };
        s.push_str(&format!(
            "\n## {title} (`{}`)\n\n| Number | Id | Name | Stage |\n|---|---|---|---|\n",
            kind.place()
        ));
        let mut rows = index.get(&kind).cloned().unwrap_or_default();
        rows.sort();
        for (n, id, name, stage) in rows {
            s.push_str(&format!("| {n} | `{id}` | {name} | {stage} |\n"));
        }
    }
    s
}

fn parse_lock(text: &str, problems: &mut Vec<Problem>) -> BTreeMap<String, KindLock> {
    let mut out: BTreeMap<String, KindLock> = BTreeMap::new();
    let table: toml::Table = match toml::from_str(text) {
        Ok(t) => t,
        Err(e) => {
            problems.push(at(LOCK_FILE, 1, e.message().to_string()));
            return out;
        }
    };
    for (kind, v) in table {
        if !Kind::ALL.iter().any(|k| k.name() == kind) {
            problems.push(at(LOCK_FILE, 1, format!("[{kind}] is not a kind of entry")));
            continue;
        }
        let mut lock = KindLock::default();
        let Some(t) = v.as_table() else {
            problems.push(at(LOCK_FILE, 1, format!("[{kind}] is not a table")));
            continue;
        };
        for (id, n) in t {
            if id == "retired" {
                for (rid, rn) in n.as_table().into_iter().flatten() {
                    match rn.as_integer().and_then(|x| u16::try_from(x).ok()) {
                        Some(x) => {
                            lock.retired.insert(rid.clone(), x);
                        }
                        None => problems.push(at(LOCK_FILE, 1, format!("{kind}.retired.{rid} is not a number"))),
                    }
                }
            } else {
                match n.as_integer().and_then(|x| u16::try_from(x).ok()) {
                    Some(x) => {
                        lock.live.insert(id.clone(), x);
                    }
                    None => problems.push(at(LOCK_FILE, 1, format!("{kind}.{id} is not a number"))),
                }
            }
        }
        // No number is given twice, live or retired.
        let mut numbers: Vec<u16> = lock.live.values().chain(lock.retired.values()).copied().collect();
        numbers.sort_unstable();
        if numbers.windows(2).any(|w| w[0] == w[1]) {
            problems.push(at(LOCK_FILE, 1, format!("[{kind}] gives a number twice")));
        }
        out.insert(kind, lock);
    }
    out
}

fn lock_text(locks: &BTreeMap<String, KindLock>) -> String {
    let mut s = String::from(
        "# Permanent numbers of every catalogue entry, per kind (A3.6), written by `kd catalog build --assign`, never by\n\
         # hand. A removed entry's number stays, under its kind's `retired` table, and no number is ever given twice.\n",
    );
    for (kind, lock) in locks {
        if lock.live.is_empty() && lock.retired.is_empty() {
            continue;
        }
        s.push_str(&format!("\n[{kind}]\n"));
        let mut live: Vec<(&String, &u16)> = lock.live.iter().collect();
        live.sort_by_key(|(_, n)| **n);
        for (id, n) in live {
            s.push_str(&format!("{id} = {n}\n"));
        }
        if !lock.retired.is_empty() {
            s.push_str(&format!("\n[{kind}.retired]\n"));
            for (id, n) in &lock.retired {
                s.push_str(&format!("{id} = {n}\n"));
            }
        }
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    const VERSION: &str = "major = 1\nminor = 0\ngenerator = 1\n";

    fn colours() -> String {
        "# Fixed colours\n\nThe palette's fixed colours.\n\n## Void\n\nNothing.\n\n```toml\nid = \"void\"\nname = \"Void\"\nstage = \"MIL-01\"\nchecks = [\"PRE-01\"]\nvalue = \"#000000\"\nuse = \"nothing drawn\"\n```\n\n## Ink\n\nOutlines.\n\n```toml\nid = \"ink\"\nname = \"Ink\"\nstage = \"MIL-01\"\nchecks = [\"PRE-01\"]\nvalue = \"#14121a\"\nuse = \"figures' outlines\"\n```\n".to_string()
    }

    fn looks() -> String {
        "# Looks\n\nMaterials.\n\n## Limestone\n\nPale rock.\n\n```toml\nid = \"limestone\"\nname = \"Limestone\"\nstage = \"MIL-01\"\nchecks = [\"PRE-20\"]\ncolour = \"#c8c4b8\"\nsteps = 6\n```\n".to_string()
    }

    fn air() -> String {
        "# The air\n\nThe light model's numbers.\n\n## Air\n\nA fine summer day.\n\n```toml\nid = \"air\"\nname = \"Air\"\nstage = \"MIL-01\"\nchecks = [\"PRE-30\"]\nwavelengths_nm = [680.0, 550.0, 440.0]\nrayleigh = [0.041, 0.097, 0.243]\nturbidity = 0.08\naerosol_exponent = 1.3\nozone = [0.02, 0.027, 0.002]\nsky_rayleigh_share = 0.5\nsky_aerosol_share = 0.7\nhorizon_sky = 0.04\nhorizon_fade_deg = 3.0\ntwilight_end_deg = -12.0\ntwilight_fall_deg = 1.2\ntwilight_ozone_per_deg = 10.0\nmoon_weakness = 400000.0\nmoon_tint = [0.9, 0.95, 1.0]\nstarlight = 2e-8\nexposure_scale = 2.0\nexposure_power = 0.85\nrods_start = 1e-4\nrods_full = 1e-7\ngrade_chroma = 1.2\nhaze_levels = [0.1, 0.25, 0.45]\nhaze_mixes = [0.15, 0.33, 0.55]\nhaze_g = 0.7\naerosol_height_m = 1200.0\nrayleigh_height_m = 8000.0\n```\n".to_string()
    }

    fn sources(colours: String, looks: String, air: String) -> Vec<Source> {
        let src = |p: &str, t: String| Source {
            path: p.into(),
            text: t,
        };
        vec![
            src(VERSION_FILE, VERSION.into()),
            src(Kind::Colour.place(), colours),
            src(Kind::Look.place(), looks),
            src(Kind::Light.place(), air),
        ]
    }

    /// The sample made clean: numbers assigned, tables and index written.
    fn clean() -> Vec<Source> {
        let mut s = sources(colours(), looks(), air());
        let out = compile(&s, true).expect("the sample compiles");
        s.push(Source {
            path: LOCK_FILE.into(),
            text: out.lock.clone(),
        });
        for (path, text) in out.stale {
            match s.iter_mut().find(|x| x.path == path) {
                Some(x) => x.text = text,
                None => s.push(Source { path, text }),
            }
        }
        s
    }

    fn with(sources: &[Source], path: &str, old: &str, new: &str) -> Vec<Source> {
        let mut s = sources.to_vec();
        let f = s.iter_mut().find(|x| x.path == path).expect("the file");
        assert!(f.text.contains(old), "{old:?} not in {path}");
        f.text = f.text.replacen(old, new, 1);
        s
    }

    fn fails(sources: &[Source], says: &str) {
        match compile(sources, false) {
            Err(p) => assert!(p.iter().any(|x| x.to_string().contains(says)), "{says}: {p:?}"),
            Ok(_) => panic!("compiled, but must fail with: {says}"),
        }
    }

    // checks: MAT-13 MAT-17 PLT-09
    #[test]
    fn clean_sample_compiles() {
        let s = clean();
        let out = compile(&s, false).expect("compiles");
        assert!(
            out.stale.is_empty(),
            "{:?}",
            out.stale.iter().map(|x| &x.0).collect::<Vec<_>>()
        );
        assert_eq!(out.entries, 4);
        let cat = &out.catalogue;
        assert_eq!(
            (cat.colours[0].id.as_str(), cat.colours[1].rgb),
            ("void", [0x14, 0x12, 0x1a])
        );
        assert_eq!((cat.looks[0].steps, cat.air.turbidity), (6, 0.08));
        assert_eq!(Catalogue::load(&out.blob).as_ref(), Ok(cat));
        // The lock gives numbers in order of appearance, kinds in name order.
        assert!(out.lock.contains("[colour]\nvoid = 0\nink = 1\n"), "{}", out.lock);
        // The tables say what the blocks hold.
        let looks = &s.iter().find(|x| x.path == Kind::Look.place()).expect("looks").text;
        assert!(
            looks.contains("| Colour under white light | #c8c4b8 |\n| Steps | 6 |"),
            "{looks}"
        );
    }

    // checks: MAT-17
    #[test]
    fn rule_1_one_block_and_known_fields() {
        let s = clean();
        fails(
            &with(
                &s,
                Kind::Look.place(),
                "```toml\nid = \"limestone\"",
                "```toml\nid = \"x\"\n```\n\n```toml\nid = \"limestone\"",
            ),
            "2 toml blocks",
        );
        fails(
            &with(&s, Kind::Look.place(), "steps = 6", "steps = 6\nshine = 1"),
            "unknown field `shine`",
        );
        fails(
            &with(&s, Kind::Look.place(), "steps = 6\n", ""),
            "missing field `steps`",
        );
        fails(
            &with(&s, Kind::Look.place(), "steps = 6", "steps = 9"),
            "a look has 4 to 7",
        );
        fails(
            &with(&s, Kind::Colour.place(), "value = \"#14121a\"", "value = \"#14121\""),
            "is not #rrggbb",
        );
        fails(
            &with(&s, Kind::Light.place(), "turbidity = 0.08", "turbidity = 1.5"),
            "turbidity outside",
        );
        fails(
            &with(&s, Kind::Colour.place(), "# Fixed colours", "Fixed colours"),
            "opens with a # title",
        );
    }

    // checks: MAT-17 PLT-09
    #[test]
    fn rule_2_ids_names_and_numbers() {
        let s = clean();
        fails(
            &with(&s, Kind::Look.place(), "id = \"limestone\"", "id = \"Lime-stone\""),
            "not snake_case",
        );
        fails(
            &with(&s, Kind::Look.place(), "name = \"Limestone\"", "name = \"Chalk\""),
            "is not the heading",
        );
        fails(
            &with(&s, Kind::Colour.place(), "id = \"ink\"", "id = \"void\""),
            "used twice",
        );
        fails(
            &with(&s, Kind::Look.place(), "id = \"limestone\"", "id = \"chalk\""),
            "has no number",
        );
        fails(
            &with(
                &s,
                LOCK_FILE,
                "[look]\nlimestone = 0\n",
                "[look]\n\n[look.retired]\nlimestone = 0\n",
            ),
            "is retired",
        );
        fails(&with(&s, LOCK_FILE, "ink = 1", "ink = 0"), "gives a number twice");
        fails(
            &with(&s, Kind::Look.place(), "stage = \"MIL-01\"", "stage = \"soon\""),
            "not a milestone",
        );
        // Assigning gives a new entry the next number, never a retired one.
        let renamed = with(&s, Kind::Look.place(), "id = \"limestone\"", "id = \"chalk\"");
        let retired = with(
            &renamed,
            LOCK_FILE,
            "[look]\nlimestone = 0\n",
            "[look]\n\n[look.retired]\nlimestone = 0\n",
        );
        let out = compile(&retired, true).expect("assigns");
        assert!(out.lock.contains("[look]\nchalk = 1\n"), "{}", out.lock);
    }

    // checks: MAT-17
    #[test]
    fn rule_4_and_files_claimed() {
        // Rule 4 (references resolve): the kinds so far name no other entry; a stray file no kind claims fails.
        let mut s = clean();
        s.push(Source {
            path: "data/palette/stray.md".into(),
            text: "# Stray\n".into(),
        });
        fails(&s, "no kind of entry claims this file");
        let mut two_airs = clean();
        let a = two_airs
            .iter_mut()
            .find(|x| x.path == Kind::Light.place())
            .expect("air");
        a.text = a.text.clone()
            + &a.text
                .replace("# The air\n", "")
                .replace("id = \"air\"", "id = \"air_two\"");
        match compile(&two_airs, true) {
            Err(p) => assert!(p.iter().any(|x| x.message.contains("2 entries of air")), "{p:?}"),
            Ok(_) => panic!("compiled with two airs"),
        }
    }

    /// The repository's own catalogue, as the build script reads it.
    fn real() -> Vec<Source> {
        let src = |p: &str, t: &str| Source {
            path: p.into(),
            text: t.into(),
        };
        vec![
            src(VERSION_FILE, include_str!("../../../data/VERSION.toml")),
            src(LOCK_FILE, include_str!("../../../data/ids.lock")),
            src(INDEX_FILE, include_str!("../../../data/INDEX.md")),
            src(Kind::Colour.place(), include_str!("../../../data/palette/colours.md")),
            src(Kind::Look.place(), include_str!("../../../data/palette/looks.md")),
            src(Kind::Light.place(), include_str!("../../../data/palette/light.md")),
        ]
    }

    // checks: PRE-34 PRE-01
    #[test]
    fn text_contrast() {
        // Body text is at least 7:1 on its panel (A11.3, A12.1); dim text, words and links at least 4.5:1.
        let cat = compile(&real(), false).expect("the catalogue compiles").catalogue;
        let luminance = |id: &str| {
            let c = cat
                .colour(id)
                .expect("a fixed colour")
                .rgb
                .map(|v| crate::schema::srgb_to_linear(f32::from(v) / 255.0));
            0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]
        };
        let ratio = |a: &str, b: &str| (luminance(a) + 0.05) / (luminance(b) + 0.05);
        assert!(ratio("ui_text", "ui_panel") >= 7.0, "{}", ratio("ui_text", "ui_panel"));
        for id in ["ui_text_dim", "ui_word", "ui_link", "ui_select"] {
            assert!(ratio(id, "ui_panel") >= 4.5, "{id}: {}", ratio(id, "ui_panel"));
        }
    }

    // checks: MAT-13 MAT-17
    #[test]
    fn real_catalogue_is_clean() {
        let out = compile(&real(), false).expect("the catalogue compiles");
        assert!(
            out.stale.is_empty(),
            "stale: {:?}",
            out.stale.iter().map(|x| &x.0).collect::<Vec<_>>()
        );
        assert_eq!(out.lock, include_str!("../../../data/ids.lock"));
        let looks: Vec<&str> = out.catalogue.looks.iter().map(|l| l.id.as_str()).collect();
        assert_eq!(looks, ["grass_lush", "grass_dry", "dirt", "limestone", "scree"]);
        assert_eq!(
            out.catalogue.air.turbidity, 0.08,
            "the owner's choice of 3 October 2026"
        );
    }

    // checks: MAT-17
    #[test]
    fn rule_6_checks_named_and_tables_current() {
        let s = clean();
        fails(
            &with(&s, Kind::Look.place(), "checks = [\"PRE-20\"]", "checks = []"),
            "names no checks",
        );
        fails(
            &with(&s, Kind::Look.place(), "checks = [\"PRE-20\"]", "checks = [\"colour\"]"),
            "not an ID",
        );
        // A block changed without its table: the table is stale, and tables rewrites it.
        let changed = with(&s, Kind::Look.place(), "steps = 6", "steps = 5");
        let out = compile(&changed, false).expect("compiles");
        assert_eq!(
            out.stale.len(),
            1,
            "only the looks' table: {:?}",
            out.stale.iter().map(|x| &x.0).collect::<Vec<_>>()
        );
        assert!(out.stale[0].1.contains("| Steps | 5 |"));
        // An entry with no table yet gets one before its block.
        let looks = &s.iter().find(|x| x.path == Kind::Look.place()).expect("looks").text;
        let (a, b) = (
            looks.find(TABLE_START).expect("a table"),
            looks.find(TABLE_END).expect("its end"),
        );
        let bare = with(&s, Kind::Look.place(), &looks[a..b + TABLE_END.len() + 2], "");
        let out = compile(&bare, false).expect("compiles");
        assert_eq!(out.stale.len(), 1);
        assert_eq!(&out.stale[0].1, looks);
    }
}
