[package]
name = "kd-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "kd"
path = "src/main.rs"

[dependencies]
kd-core.workspace = true
kd-data.workspace = true
kd-world.workspace = true
kd-things.workspace = true
kd-sim.workspace = true
kd-save.workspace = true
kd-text.workspace = true
kd-audio.workspace = true
