[package]
name = "kd-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kd-player.workspace = true
kd-culture.workspace = true
kd-people.workspace = true
kd-world.workspace = true
kd-things.workspace = true
kd-life.workspace = true
kd-data.workspace = true
kd-core.workspace = true
kd-view.workspace = true
