[package]
name = "kd-culture"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kd-people.workspace = true
kd-world.workspace = true
kd-things.workspace = true
kd-life.workspace = true
kd-core.workspace = true
kd-data.workspace = true
