// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod kfb {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

// struct Cell, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Cell(pub [u8; 32]);
impl Default for Cell { 
  fn default() -> Self { 
    Self([0; 32])
  }
}
impl core::fmt::Debug for Cell {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Cell")
      .field("elev", &self.elev())
      .field("water", &self.water())
      .field("soil", &self.soil())
      .field("veg", &self.veg())
      .field("snow", &self.snow())
      .field("temp", &self.temp())
      .field("flags", &self.flags())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Cell {}
impl flatbuffers::SafeSliceAccess for Cell {}
impl<'a> flatbuffers::Follow<'a> for Cell {
  type Inner = &'a Cell;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Cell>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Cell {
  type Inner = &'a Cell;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Cell>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Cell {
    type Output = Cell;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Cell as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Cell {
    type Output = Cell;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Cell as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Cell {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Cell {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    elev: f32,
    water: f32,
    soil: &[u16; 4],
    veg: &[u16; 4],
    snow: u16,
    temp: i16,
    flags: u32,
  ) -> Self {
    let mut s = Self([0; 32]);
    s.set_elev(elev);
    s.set_water(water);
    s.set_soil(soil);
    s.set_veg(veg);
    s.set_snow(snow);
    s.set_temp(temp);
    s.set_flags(flags);
    s
  }

  pub fn elev(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<f32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_elev(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<f32>(),
      );
    }
  }

  pub fn water(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<f32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_water(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f32 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<f32>(),
      );
    }
  }

  pub fn soil(&'a self) -> flatbuffers::Array<'a, u16, 4> {
    flatbuffers::Array::follow(&self.0, 8)
  }

  pub fn set_soil(&mut self, items: &[u16; 4]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 8, items);
  }

  pub fn veg(&'a self) -> flatbuffers::Array<'a, u16, 4> {
    flatbuffers::Array::follow(&self.0, 16)
  }

  pub fn set_veg(&mut self, items: &[u16; 4]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 16, items);
  }

  pub fn snow(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[24..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_snow(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[24..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn temp(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[26..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_temp(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[26..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn flags(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[28..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_flags(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[28..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

}

// struct Patch, aligned to 2
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Patch(pub [u8; 8]);
impl Default for Patch { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl core::fmt::Debug for Patch {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Patch")
      .field("b", &self.b())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Patch {}
impl flatbuffers::SafeSliceAccess for Patch {}
impl<'a> flatbuffers::Follow<'a> for Patch {
  type Inner = &'a Patch;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Patch>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Patch {
  type Inner = &'a Patch;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Patch>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Patch {
    type Output = Patch;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Patch as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Patch {
    type Output = Patch;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Patch as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Patch {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Patch {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    b: &[u16; 4],
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_b(b);
    s
  }

  pub fn b(&'a self) -> flatbuffers::Array<'a, u16, 4> {
    flatbuffers::Array::follow(&self.0, 0)
  }

  pub fn set_b(&mut self, items: &[u16; 4]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 0, items);
  }

}

// struct Animal, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Animal(pub [u8; 32]);
impl Default for Animal { 
  fn default() -> Self { 
    Self([0; 32])
  }
}
impl core::fmt::Debug for Animal {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Animal")
      .field("id", &self.id())
      .field("species", &self.species())
      .field("flags", &self.flags())
      .field("x", &self.x())
      .field("y", &self.y())
      .field("energy", &self.energy())
      .field("health", &self.health())
      .field("age", &self.age())
      .field("herd", &self.herd())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Animal {}
impl flatbuffers::SafeSliceAccess for Animal {}
impl<'a> flatbuffers::Follow<'a> for Animal {
  type Inner = &'a Animal;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Animal>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Animal {
  type Inner = &'a Animal;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Animal>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Animal {
    type Output = Animal;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Animal as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Animal {
    type Output = Animal;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Animal as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Animal {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Animal {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    id: u32,
    species: u16,
    flags: u16,
    x: u32,
    y: u32,
    energy: f32,
    health: f32,
    age: u32,
    herd: u32,
  ) -> Self {
    let mut s = Self([0; 32]);
    s.set_id(id);
    s.set_species(species);
    s.set_flags(flags);
    s.set_x(x);
    s.set_y(y);
    s.set_energy(energy);
    s.set_health(health);
    s.set_age(age);
    s.set_herd(herd);
    s
  }

  pub fn id(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_id(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn species(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_species(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn flags(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[6..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_flags(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[6..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn x(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_x(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn y(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_y(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn energy(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<f32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_energy(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f32 as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<f32>(),
      );
    }
  }

  pub fn health(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<f32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[20..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_health(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f32 as *const u8,
        self.0[20..].as_mut_ptr(),
        core::mem::size_of::<f32>(),
      );
    }
  }

  pub fn age(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[24..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_age(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[24..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn herd(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[28..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_herd(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[28..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

}

// struct Thing, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Thing(pub [u8; 32]);
impl Default for Thing { 
  fn default() -> Self { 
    Self([0; 32])
  }
}
impl core::fmt::Debug for Thing {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Thing")
      .field("id", &self.id())
      .field("kind", &self.kind())
      .field("material", &self.material())
      .field("x", &self.x())
      .field("y", &self.y())
      .field("z", &self.z())
      .field("condition", &self.condition())
      .field("mass", &self.mass())
      .field("owner", &self.owner())
      .field("made", &self.made())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Thing {}
impl flatbuffers::SafeSliceAccess for Thing {}
impl<'a> flatbuffers::Follow<'a> for Thing {
  type Inner = &'a Thing;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Thing>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Thing {
  type Inner = &'a Thing;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Thing>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Thing {
    type Output = Thing;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Thing as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Thing {
    type Output = Thing;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Thing as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Thing {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Thing {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    id: u32,
    kind: u16,
    material: u16,
    x: u32,
    y: u32,
    z: i16,
    condition: u16,
    mass: u32,
    owner: u32,
    made: i32,
  ) -> Self {
    let mut s = Self([0; 32]);
    s.set_id(id);
    s.set_kind(kind);
    s.set_material(material);
    s.set_x(x);
    s.set_y(y);
    s.set_z(z);
    s.set_condition(condition);
    s.set_mass(mass);
    s.set_owner(owner);
    s.set_made(made);
    s
  }

  pub fn id(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_id(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn kind(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_kind(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn material(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[6..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_material(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[6..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn x(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_x(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn y(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_y(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn z(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_z(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn condition(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[18..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_condition(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[18..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn mass(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[20..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_mass(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[20..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn owner(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[24..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_owner(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[24..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn made(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<i32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[28..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_made(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i32 as *const u8,
        self.0[28..].as_mut_ptr(),
        core::mem::size_of::<i32>(),
      );
    }
  }

}

// struct Memory, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Memory(pub [u8; 24]);
impl Default for Memory { 
  fn default() -> Self { 
    Self([0; 24])
  }
}
impl core::fmt::Debug for Memory {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Memory")
      .field("day", &self.day())
      .field("kind", &self.kind())
      .field("valence", &self.valence())
      .field("subject", &self.subject())
      .field("place", &self.place())
      .field("strength", &self.strength())
      .field("detail", &self.detail())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Memory {}
impl flatbuffers::SafeSliceAccess for Memory {}
impl<'a> flatbuffers::Follow<'a> for Memory {
  type Inner = &'a Memory;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Memory>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Memory {
  type Inner = &'a Memory;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Memory>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Memory {
    type Output = Memory;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Memory as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Memory {
    type Output = Memory;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Memory as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Memory {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Memory {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    day: i32,
    kind: u16,
    valence: i16,
    subject: u32,
    place: u32,
    strength: f32,
    detail: u32,
  ) -> Self {
    let mut s = Self([0; 24]);
    s.set_day(day);
    s.set_kind(kind);
    s.set_valence(valence);
    s.set_subject(subject);
    s.set_place(place);
    s.set_strength(strength);
    s.set_detail(detail);
    s
  }

  pub fn day(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<i32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_day(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<i32>(),
      );
    }
  }

  pub fn kind(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_kind(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn valence(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[6..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_valence(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[6..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn subject(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_subject(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn place(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_place(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn strength(&self) -> f32 {
    let mut mem = core::mem::MaybeUninit::<f32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<f32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_strength(&mut self, x: f32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const f32 as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<f32>(),
      );
    }
  }

  pub fn detail(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[20..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_detail(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[20..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

}

// struct Relation, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Relation(pub [u8; 16]);
impl Default for Relation { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for Relation {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Relation")
      .field("other", &self.other())
      .field("kind", &self.kind())
      .field("trust", &self.trust())
      .field("affection", &self.affection())
      .field("fear", &self.fear())
      .field("last_day", &self.last_day())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Relation {}
impl flatbuffers::SafeSliceAccess for Relation {}
impl<'a> flatbuffers::Follow<'a> for Relation {
  type Inner = &'a Relation;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Relation>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Relation {
  type Inner = &'a Relation;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Relation>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Relation {
    type Output = Relation;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const Relation as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b Relation {
    type Output = Relation;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const Relation as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Relation {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Relation {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    other: u32,
    kind: u16,
    trust: i16,
    affection: i16,
    fear: i16,
    last_day: i32,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_other(other);
    s.set_kind(kind);
    s.set_trust(trust);
    s.set_affection(affection);
    s.set_fear(fear);
    s.set_last_day(last_day);
    s
  }

  pub fn other(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_other(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn kind(&self) -> u16 {
    let mut mem = core::mem::MaybeUninit::<u16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_kind(&mut self, x: u16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u16 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<u16>(),
      );
    }
  }

  pub fn trust(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[6..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_trust(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[6..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn affection(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_affection(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn fear(&self) -> i16 {
    let mut mem = core::mem::MaybeUninit::<i16>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[10..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i16>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_fear(&mut self, x: i16) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i16 as *const u8,
        self.0[10..].as_mut_ptr(),
        core::mem::size_of::<i16>(),
      );
    }
  }

  pub fn last_day(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<i32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_last_day(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i32 as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<i32>(),
      );
    }
  }

}

// struct PersonCore, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct PersonCore(pub [u8; 256]);
impl Default for PersonCore { 
  fn default() -> Self { 
    Self([0; 256])
  }
}
impl core::fmt::Debug for PersonCore {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("PersonCore")
      .field("id", &self.id())
      .field("born", &self.born())
      .field("x", &self.x())
      .field("y", &self.y())
      .field("band", &self.band())
      .field("flags", &self.flags())
      .field("body", &self.body())
      .field("needs", &self.needs())
      .field("feel", &self.feel())
      .field("skills", &self.skills())
      .field("traits", &self.traits())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for PersonCore {}
impl flatbuffers::SafeSliceAccess for PersonCore {}
impl<'a> flatbuffers::Follow<'a> for PersonCore {
  type Inner = &'a PersonCore;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a PersonCore>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a PersonCore {
  type Inner = &'a PersonCore;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<PersonCore>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for PersonCore {
    type Output = PersonCore;
    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(self as *const PersonCore as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}
impl<'b> flatbuffers::Push for &'b PersonCore {
    type Output = PersonCore;

    #[inline]
    fn push(&self, dst: &mut [u8], _rest: &[u8]) {
        let src = unsafe {
            ::core::slice::from_raw_parts(*self as *const PersonCore as *const u8, Self::size())
        };
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for PersonCore {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> PersonCore {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    id: u32,
    born: i32,
    x: u32,
    y: u32,
    band: u32,
    flags: u32,
    body: &[f32; 16],
    needs: &[f32; 8],
    feel: &[f32; 8],
    skills: &[u16; 32],
    traits: &[u8; 40],
  ) -> Self {
    let mut s = Self([0; 256]);
    s.set_id(id);
    s.set_born(born);
    s.set_x(x);
    s.set_y(y);
    s.set_band(band);
    s.set_flags(flags);
    s.set_body(body);
    s.set_needs(needs);
    s.set_feel(feel);
    s.set_skills(skills);
    s.set_traits(traits);
    s
  }

  pub fn id(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_id(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn born(&self) -> i32 {
    let mut mem = core::mem::MaybeUninit::<i32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<i32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_born(&mut self, x: i32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const i32 as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<i32>(),
      );
    }
  }

  pub fn x(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_x(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn y(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_y(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn band(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_band(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn flags(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<u32>::uninit();
    unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[20..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<u32>(),
      );
      mem.assume_init()
    }.from_little_endian()
  }

  pub fn set_flags(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const u32 as *const u8,
        self.0[20..].as_mut_ptr(),
        core::mem::size_of::<u32>(),
      );
    }
  }

  pub fn body(&'a self) -> flatbuffers::Array<'a, f32, 16> {
    flatbuffers::Array::follow(&self.0, 24)
  }

  pub fn set_body(&mut self, items: &[f32; 16]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 24, items);
  }

  pub fn needs(&'a self) -> flatbuffers::Array<'a, f32, 8> {
    flatbuffers::Array::follow(&self.0, 88)
  }

  pub fn set_needs(&mut self, items: &[f32; 8]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 88, items);
  }

  pub fn feel(&'a self) -> flatbuffers::Array<'a, f32, 8> {
    flatbuffers::Array::follow(&self.0, 120)
  }

  pub fn set_feel(&mut self, items: &[f32; 8]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 120, items);
  }

  pub fn skills(&'a self) -> flatbuffers::Array<'a, u16, 32> {
    flatbuffers::Array::follow(&self.0, 152)
  }

  pub fn set_skills(&mut self, items: &[u16; 32]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 152, items);
  }

  pub fn traits(&'a self) -> flatbuffers::Array<'a, u8, 40> {
    flatbuffers::Array::follow(&self.0, 216)
  }

  pub fn set_traits(&mut self, items: &[u8; 40]) {
    flatbuffers::emplace_scalar_array(&mut self.0, 216, items);
  }

}

pub enum PersonOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Person<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Person<'a> {
  type Inner = Person<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Person<'a> {
  pub const VT_CORE: flatbuffers::VOffsetT = 4;
  pub const VT_MEMORIES: flatbuffers::VOffsetT = 6;
  pub const VT_RELATIONS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Person { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args PersonArgs<'args>
  ) -> flatbuffers::WIPOffset<Person<'bldr>> {
    let mut builder = PersonBuilder::new(_fbb);
    if let Some(x) = args.relations { builder.add_relations(x); }
    if let Some(x) = args.memories { builder.add_memories(x); }
    if let Some(x) = args.core { builder.add_core(x); }
    builder.finish()
  }


  #[inline]
  pub fn core(&self) -> Option<&'a PersonCore> {
    self._tab.get::<PersonCore>(Person::VT_CORE, None)
  }
  #[inline]
  pub fn memories(&self) -> Option<&'a [Memory]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Memory>>>(Person::VT_MEMORIES, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn relations(&self) -> Option<&'a [Relation]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Relation>>>(Person::VT_RELATIONS, None).map(|v| v.safe_slice())
  }
}

impl flatbuffers::Verifiable for Person<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<PersonCore>("core", Self::VT_CORE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Memory>>>("memories", Self::VT_MEMORIES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Relation>>>("relations", Self::VT_RELATIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct PersonArgs<'a> {
    pub core: Option<&'a PersonCore>,
    pub memories: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Memory>>>,
    pub relations: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Relation>>>,
}
impl<'a> Default for PersonArgs<'a> {
  #[inline]
  fn default() -> Self {
    PersonArgs {
      core: None,
      memories: None,
      relations: None,
    }
  }
}

pub struct PersonBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> PersonBuilder<'a, 'b> {
  #[inline]
  pub fn add_core(&mut self, core: &PersonCore) {
    self.fbb_.push_slot_always::<&PersonCore>(Person::VT_CORE, core);
  }
  #[inline]
  pub fn add_memories(&mut self, memories: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Memory>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Person::VT_MEMORIES, memories);
  }
  #[inline]
  pub fn add_relations(&mut self, relations: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Relation>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Person::VT_RELATIONS, relations);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> PersonBuilder<'a, 'b> {
    let start = _fbb.start_table();
    PersonBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Person<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Person<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Person");
      ds.field("core", &self.core());
      ds.field("memories", &self.memories());
      ds.field("relations", &self.relations());
      ds.finish()
  }
}
pub enum RegionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Region<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Region<'a> {
  type Inner = Region<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Region<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_HASH: flatbuffers::VOffsetT = 6;
  pub const VT_CELLS: flatbuffers::VOffsetT = 8;
  pub const VT_PATCHES: flatbuffers::VOffsetT = 10;
  pub const VT_PEOPLE: flatbuffers::VOffsetT = 12;
  pub const VT_ANIMALS: flatbuffers::VOffsetT = 14;
  pub const VT_THINGS: flatbuffers::VOffsetT = 16;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Region { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args RegionArgs<'args>
  ) -> flatbuffers::WIPOffset<Region<'bldr>> {
    let mut builder = RegionBuilder::new(_fbb);
    builder.add_hash(args.hash);
    if let Some(x) = args.things { builder.add_things(x); }
    if let Some(x) = args.animals { builder.add_animals(x); }
    if let Some(x) = args.people { builder.add_people(x); }
    if let Some(x) = args.patches { builder.add_patches(x); }
    if let Some(x) = args.cells { builder.add_cells(x); }
    builder.add_id(args.id);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u16 {
    self._tab.get::<u16>(Region::VT_ID, Some(0)).unwrap()
  }
  #[inline]
  pub fn hash(&self) -> u64 {
    self._tab.get::<u64>(Region::VT_HASH, Some(0)).unwrap()
  }
  #[inline]
  pub fn cells(&self) -> Option<&'a [Cell]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Cell>>>(Region::VT_CELLS, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn patches(&self) -> Option<&'a [Patch]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Patch>>>(Region::VT_PATCHES, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn people(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Person<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Person>>>>(Region::VT_PEOPLE, None)
  }
  #[inline]
  pub fn animals(&self) -> Option<&'a [Animal]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Animal>>>(Region::VT_ANIMALS, None).map(|v| v.safe_slice())
  }
  #[inline]
  pub fn things(&self) -> Option<&'a [Thing]> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Thing>>>(Region::VT_THINGS, None).map(|v| v.safe_slice())
  }
}

impl flatbuffers::Verifiable for Region<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("id", Self::VT_ID, false)?
     .visit_field::<u64>("hash", Self::VT_HASH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Cell>>>("cells", Self::VT_CELLS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Patch>>>("patches", Self::VT_PATCHES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Person>>>>("people", Self::VT_PEOPLE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Animal>>>("animals", Self::VT_ANIMALS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Thing>>>("things", Self::VT_THINGS, false)?
     .finish();
    Ok(())
  }
}
pub struct RegionArgs<'a> {
    pub id: u16,
    pub hash: u64,
    pub cells: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Cell>>>,
    pub patches: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Patch>>>,
    pub people: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Person<'a>>>>>,
    pub animals: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Animal>>>,
    pub things: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Thing>>>,
}
impl<'a> Default for RegionArgs<'a> {
  #[inline]
  fn default() -> Self {
    RegionArgs {
      id: 0,
      hash: 0,
      cells: None,
      patches: None,
      people: None,
      animals: None,
      things: None,
    }
  }
}

pub struct RegionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> RegionBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: u16) {
    self.fbb_.push_slot::<u16>(Region::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_hash(&mut self, hash: u64) {
    self.fbb_.push_slot::<u64>(Region::VT_HASH, hash, 0);
  }
  #[inline]
  pub fn add_cells(&mut self, cells: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Cell>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Region::VT_CELLS, cells);
  }
  #[inline]
  pub fn add_patches(&mut self, patches: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Patch>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Region::VT_PATCHES, patches);
  }
  #[inline]
  pub fn add_people(&mut self, people: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Person<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Region::VT_PEOPLE, people);
  }
  #[inline]
  pub fn add_animals(&mut self, animals: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Animal>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Region::VT_ANIMALS, animals);
  }
  #[inline]
  pub fn add_things(&mut self, things: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Thing>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Region::VT_THINGS, things);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> RegionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    RegionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Region<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Region<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Region");
      ds.field("id", &self.id());
      ds.field("hash", &self.hash());
      ds.field("cells", &self.cells());
      ds.field("patches", &self.patches());
      ds.field("people", &self.people());
      ds.field("animals", &self.animals());
      ds.field("things", &self.things());
      ds.finish()
  }
}
pub enum MomentOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Moment<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Moment<'a> {
  type Inner = Moment<'a>;
  #[inline]
  fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table { buf, loc } }
  }
}

impl<'a> Moment<'a> {
  pub const VT_DAY: flatbuffers::VOffsetT = 4;
  pub const VT_SEED: flatbuffers::VOffsetT = 6;
  pub const VT_W: flatbuffers::VOffsetT = 8;
  pub const VT_H: flatbuffers::VOffsetT = 10;
  pub const VT_NP: flatbuffers::VOffsetT = 12;
  pub const VT_NA: flatbuffers::VOffsetT = 14;
  pub const VT_NT: flatbuffers::VOffsetT = 16;
  pub const VT_REGIONS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Moment { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args MomentArgs<'args>
  ) -> flatbuffers::WIPOffset<Moment<'bldr>> {
    let mut builder = MomentBuilder::new(_fbb);
    builder.add_seed(args.seed);
    builder.add_day(args.day);
    if let Some(x) = args.regions { builder.add_regions(x); }
    builder.add_nt(args.nt);
    builder.add_na(args.na);
    builder.add_np(args.np);
    builder.add_h(args.h);
    builder.add_w(args.w);
    builder.finish()
  }


  #[inline]
  pub fn day(&self) -> u64 {
    self._tab.get::<u64>(Moment::VT_DAY, Some(0)).unwrap()
  }
  #[inline]
  pub fn seed(&self) -> u64 {
    self._tab.get::<u64>(Moment::VT_SEED, Some(0)).unwrap()
  }
  #[inline]
  pub fn w(&self) -> u32 {
    self._tab.get::<u32>(Moment::VT_W, Some(0)).unwrap()
  }
  #[inline]
  pub fn h(&self) -> u32 {
    self._tab.get::<u32>(Moment::VT_H, Some(0)).unwrap()
  }
  #[inline]
  pub fn np(&self) -> u32 {
    self._tab.get::<u32>(Moment::VT_NP, Some(0)).unwrap()
  }
  #[inline]
  pub fn na(&self) -> u32 {
    self._tab.get::<u32>(Moment::VT_NA, Some(0)).unwrap()
  }
  #[inline]
  pub fn nt(&self) -> u32 {
    self._tab.get::<u32>(Moment::VT_NT, Some(0)).unwrap()
  }
  #[inline]
  pub fn regions(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Region<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Region>>>>(Moment::VT_REGIONS, None)
  }
}

impl flatbuffers::Verifiable for Moment<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("day", Self::VT_DAY, false)?
     .visit_field::<u64>("seed", Self::VT_SEED, false)?
     .visit_field::<u32>("w", Self::VT_W, false)?
     .visit_field::<u32>("h", Self::VT_H, false)?
     .visit_field::<u32>("np", Self::VT_NP, false)?
     .visit_field::<u32>("na", Self::VT_NA, false)?
     .visit_field::<u32>("nt", Self::VT_NT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Region>>>>("regions", Self::VT_REGIONS, false)?
     .finish();
    Ok(())
  }
}
pub struct MomentArgs<'a> {
    pub day: u64,
    pub seed: u64,
    pub w: u32,
    pub h: u32,
    pub np: u32,
    pub na: u32,
    pub nt: u32,
    pub regions: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Region<'a>>>>>,
}
impl<'a> Default for MomentArgs<'a> {
  #[inline]
  fn default() -> Self {
    MomentArgs {
      day: 0,
      seed: 0,
      w: 0,
      h: 0,
      np: 0,
      na: 0,
      nt: 0,
      regions: None,
    }
  }
}

pub struct MomentBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> MomentBuilder<'a, 'b> {
  #[inline]
  pub fn add_day(&mut self, day: u64) {
    self.fbb_.push_slot::<u64>(Moment::VT_DAY, day, 0);
  }
  #[inline]
  pub fn add_seed(&mut self, seed: u64) {
    self.fbb_.push_slot::<u64>(Moment::VT_SEED, seed, 0);
  }
  #[inline]
  pub fn add_w(&mut self, w: u32) {
    self.fbb_.push_slot::<u32>(Moment::VT_W, w, 0);
  }
  #[inline]
  pub fn add_h(&mut self, h: u32) {
    self.fbb_.push_slot::<u32>(Moment::VT_H, h, 0);
  }
  #[inline]
  pub fn add_np(&mut self, np: u32) {
    self.fbb_.push_slot::<u32>(Moment::VT_NP, np, 0);
  }
  #[inline]
  pub fn add_na(&mut self, na: u32) {
    self.fbb_.push_slot::<u32>(Moment::VT_NA, na, 0);
  }
  #[inline]
  pub fn add_nt(&mut self, nt: u32) {
    self.fbb_.push_slot::<u32>(Moment::VT_NT, nt, 0);
  }
  #[inline]
  pub fn add_regions(&mut self, regions: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Region<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Moment::VT_REGIONS, regions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> MomentBuilder<'a, 'b> {
    let start = _fbb.start_table();
    MomentBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Moment<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Moment<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Moment");
      ds.field("day", &self.day());
      ds.field("seed", &self.seed());
      ds.field("w", &self.w());
      ds.field("h", &self.h());
      ds.field("np", &self.np());
      ds.field("na", &self.na());
      ds.field("nt", &self.nt());
      ds.field("regions", &self.regions());
      ds.finish()
  }
}
#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_root_as_moment<'a>(buf: &'a [u8]) -> Moment<'a> {
  unsafe { flatbuffers::root_unchecked::<Moment<'a>>(buf) }
}

#[inline]
#[deprecated(since="2.0.0", note="Deprecated in favor of `root_as...` methods.")]
pub fn get_size_prefixed_root_as_moment<'a>(buf: &'a [u8]) -> Moment<'a> {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<Moment<'a>>(buf) }
}

#[inline]
/// Verifies that a buffer of bytes contains a `Moment`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_moment_unchecked`.
pub fn root_as_moment(buf: &[u8]) -> Result<Moment, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Moment>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Moment` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_moment_unchecked`.
pub fn size_prefixed_root_as_moment(buf: &[u8]) -> Result<Moment, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Moment>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Moment` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_moment_unchecked`.
pub fn root_as_moment_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Moment<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Moment<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Moment` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_moment_unchecked`.
pub fn size_prefixed_root_as_moment_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Moment<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Moment<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Moment and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Moment`.
pub unsafe fn root_as_moment_unchecked(buf: &[u8]) -> Moment {
  flatbuffers::root_unchecked::<Moment>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Moment and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Moment`.
pub unsafe fn size_prefixed_root_as_moment_unchecked(buf: &[u8]) -> Moment {
  flatbuffers::size_prefixed_root_unchecked::<Moment>(buf)
}
#[inline]
pub fn finish_moment_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Moment<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_moment_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Moment<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod kfb

