//! Reading catalogue sources (A3.6 step 1): every claimed file in sorted path order, split at `## ` headings outside
//! code fences, each entry's fenced `toml` blocks and its generated table found.

/// The start of a generated table (A3.6); the marker line may say more after `table`.
pub const TABLE_START: &str = "<!-- table: generated by `kd catalog tables`; edit the block, not the table -->";
/// The end of a generated table.
pub const TABLE_END: &str = "<!-- end table -->";

/// One entry's text: its heading, where it sits, its `toml` blocks and its generated table.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct RawEntry {
    pub heading: String,
    /// The heading's line, from 1.
    pub line: usize,
    /// The entry's lines in the file, from the heading to before the next heading (0-based, end exclusive).
    pub lines: (usize, usize),
    pub blocks: Vec<String>,
    /// The first `toml` fence's line (0-based), where a missing table goes.
    pub block_line: Option<usize>,
    /// The generated table's lines, both markers included (0-based, end exclusive), when it has one.
    pub table: Option<(usize, usize)>,
}

fn is_fence(line: &str) -> bool {
    line.trim_start().starts_with("```")
}

/// Splits a catalogue file into its entries; text before the first heading is the file's introduction.
pub fn split(text: &str) -> Vec<RawEntry> {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut out: Vec<RawEntry> = Vec::new();
    let mut in_fence = false;
    let mut block: Option<String> = None;
    let mut table_from: Option<usize> = None;
    for (i, line) in lines.iter().enumerate() {
        if is_fence(line) {
            if in_fence {
                if let (Some(b), Some(e)) = (block.take(), out.last_mut()) {
                    e.blocks.push(b);
                }
                in_fence = false;
            } else {
                in_fence = true;
                if line.trim() == "```toml" {
                    block = Some(String::new());
                    if let Some(e) = out.last_mut()
                        && e.block_line.is_none()
                    {
                        e.block_line = Some(i);
                    }
                }
            }
            continue;
        }
        if in_fence {
            if let Some(b) = &mut block {
                b.push_str(line);
                b.push('\n');
            }
            continue;
        }
        if let Some(h) = line.strip_prefix("## ") {
            if let Some(e) = out.last_mut() {
                e.lines.1 = i;
            }
            out.push(RawEntry {
                heading: h.trim().to_string(),
                line: i + 1,
                lines: (i, lines.len()),
                ..RawEntry::default()
            });
            table_from = None;
            continue;
        }
        if line.trim_start().starts_with("<!-- table") {
            table_from = Some(i);
        } else if line.trim() == TABLE_END
            && let (Some(from), Some(e)) = (table_from.take(), out.last_mut())
        {
            e.table = Some((from, i + 1));
        }
    }
    out
}

/// Whether an id is `snake_case`: lower-case letters, digits and single underscores, starting with a letter.
pub fn is_snake_case(id: &str) -> bool {
    let b = id.as_bytes();
    !b.is_empty()
        && b[0].is_ascii_lowercase()
        && b[b.len() - 1] != b'_'
        && !id.contains("__")
        && b.iter()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || *c == b'_')
}

/// Whether a string is a plain decimal number such as `0.42`, `-0.012` or `2`.
pub fn is_decimal(s: &str) -> bool {
    let digits = s.strip_prefix('-').unwrap_or(s);
    let mut parts = digits.split('.');
    let whole = parts.next().unwrap_or("");
    let frac = parts.next();
    parts.next().is_none()
        && !whole.is_empty()
        && whole.bytes().all(|c| c.is_ascii_digit())
        && frac.is_none_or(|f| !f.is_empty() && f.bytes().all(|c| c.is_ascii_digit()))
}

/// A `#rrggbb` colour's channels.
pub fn hex_rgb(s: &str) -> Option<[u8; 3]> {
    let h = s.strip_prefix('#')?;
    if h.len() != 6 || !h.bytes().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    let v = u32::from_str_radix(h, 16).ok()?;
    Some([(v >> 16) as u8, (v >> 8) as u8, v as u8])
}

/// The live (not Dropped) item IDs of `PROJECT.md`, from its item markers (`- `XXX-NN` **Name** *(Status)*`), the
/// section of examples (`## How this file works`) left out; and every ID with its status.
pub fn project_items(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let mut skip = false;
    for line in text.lines() {
        if line.starts_with("## ") {
            skip = line.trim() == "## How this file works";
        }
        if skip {
            continue;
        }
        let t = line.trim_start();
        let rest = if let Some(r) = t.strip_prefix("- ") {
            r
        } else {
            let digits = t.bytes().take_while(u8::is_ascii_digit).count();
            match t[digits..].strip_prefix(". ") {
                Some(r) if digits > 0 => r,
                _ => continue,
            }
        };
        let Some(r) = rest.strip_prefix('`') else { continue };
        let Some(end) = r.find('`') else { continue };
        let id = &r[..end];
        let after = &r[end + 1..];
        if !after.starts_with(" **") || !is_item_id(id) {
            continue;
        }
        let Some(s) = after.find("*(") else { continue };
        let Some(e) = after[s..].find(")*") else { continue };
        out.push((id.to_string(), after[s + 2..s + e].to_string()));
    }
    out
}

/// Whether a token is shaped like a `PROJECT.md` ID: three capitals, a dash, two or three digits.
pub fn is_item_id(s: &str) -> bool {
    let b = s.as_bytes();
    (b.len() == 6 || b.len() == 7)
        && b[..3].iter().all(u8::is_ascii_uppercase)
        && b[3] == b'-'
        && b[4..].iter().all(u8::is_ascii_digit)
}
