[package]
name = "kd-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
kd-core.workspace = true
kd-data.workspace = true
kd-view.workspace = true
kd-world.workspace = true
kd-sim.workspace = true
kd-save.workspace = true
kd-render.workspace = true
kd-ui.workspace = true
kd-audio.workspace = true
kd-text.workspace = true
glow.workspace = true
log.workspace = true

[build-dependencies]
kd-data = { workspace = true, features = ["compile"] }
