#!/usr/bin/env python3
"""Text checks over the repository (A15.12): `kd check file` and `kd check ids` are this script's modes.

    python3 tools/filecheck.py file                the file check (PRC-10) and the commit check (PRC-07), step 7
    python3 tools/filecheck.py ids --merge         the coverage check (PRC-12), the coverage map current, step 8
    python3 tools/filecheck.py map [--write]       prints the plan's coverage map, or writes it into the plan
    python3 tools/filecheck.py note                dist/NOTE.md's five headings and its APK link (PRC-11)
    python3 tools/filecheck.py gate <description>  the merge gate (A15.13 step 6, PRC-09)
    python3 tools/filecheck.py selftest            each planted fault fails with its own message; the clean
                                                   fixture passes (PRC-12)

The file check reads PROJECT.md's item markers, statuses, IDs (unique, never retired ones) and generated lists;
every ID and architecture section the three documents cite; each alpha section's eleven fields and task IDs; and
every commit since main that changes PROJECT.md. Findings awaiting the owner sit in tools/filecheck-known.txt.
Python's standard library only.
"""
import difflib
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCUMENTS = ("PROJECT.md", "ARCHITECTURE.md", "IMPLEMENTATION.md")
KNOWN = "tools/filecheck-known.txt"
FIXTURES = os.path.join(ROOT, "tools", "tests", "filecheck")

ID = r"[A-Z]{3}-\d{2,3}"
ID_RE = re.compile(rf"\b{ID}\b")
STATUSES = ("Decided", "Proposed", "To test")
MARKER = re.compile(rf"^\s*(?:- |\d+\. )`({ID})` \*\*(.+?)\*\* \*\(([^)]*)\)\*(?::.*)?$")
# Lines that set out to be markers: a list entry opening with a backticked token and a bold name, or with something
# shaped like an ID however it is wrapped, so a marker that lost its backticks or bold is still caught.
MARKER_LIKE = (re.compile(r"^\s*(?:-|\d+\.)\s+`([^`]+)`\s+\*\*"),
               re.compile(r"^\s*(?:[-*+]|\d+\.)\s+(?:\*\*)?`?([A-Z]{2,4}-?\d{1,4})\b"))
BACKTICKED = re.compile(r"`([^`\n]+)`")
RETIRED_LINE = re.compile(r"^\s*(?:- )?Retired IDs:(.*)$", re.M)
EXAMPLES = "## How this file works"  # its IDs are examples, not references
SECTION = re.compile(r"(?<![\w.#/-])(A\d{1,2}(?:\.\d{1,2})?)(?!\w)")
ARCH_HEADING = re.compile(r"^#{1,6}\s+(A\d+(?:\.\d+)*)\.?\s", re.M)
ALPHA_HEADING = re.compile(r"^### α(\d{2}[a-e]?)\b")
FIELDS = ["Goal", "Serves", "Architecture", "Needs", "Crates and files touched", "Tasks", "Data", "Tests",
          "On the phone", "Not in this alpha", "Risks"]
FIELD = re.compile(r"^\*\*([A-Z][^*:]*?):\*\*")
TASK = re.compile(r"^\d+\. `([^`]+)`")
GENERATED = re.compile(r"<!-- generated: ([a-z ]+) -->\n(.*?)<!-- end generated -->", re.S)
NOTE_HEADINGS = ["What is new", "What to try", "What is rough", "IDs delivered", "Links"]
RULES_HEADING = "## Rules every alpha keeps"
MAP_HEADING = "## Coverage map"
MAP_INTRO = (
    "Generated by `python3 tools/filecheck.py map --write`: every item of `PROJECT.md` and the alphas still to build "
    "whose **Serves** line names it (`PRC-12`); `built` marks an item the code implements (an `Implements` line) that "
    "no alpha left serves, and `every alpha` a rule every alpha keeps.\n"
    "Context items need nothing built: the milestones (`MIL`), the risks (`RSK`), and the vision's statements (`VIS`) "
    "that have no Done when or Check of their own.")


# PROJECT.md (PRC-10's file check).

class Item:
    """One PROJECT.md item: ID, name, status, and its lines (0-based, from its marker to the line before the next
    marker or heading)."""

    def __init__(self, id_, name, status, line):
        self.id, self.name, self.status, self.start, self.end = id_, name, status, line, line


def without_examples(text):
    """PROJECT.md's lines with `## How this file works` blanked, since its IDs are examples."""
    out, skip = [], False
    for line in text.split("\n"):
        if line.startswith("## "):
            skip = line.strip() == EXAMPLES
        out.append("" if skip else line)
    return out


def retired(project):
    m = RETIRED_LINE.search(project)
    return set(ID_RE.findall(m.group(1))) if m else set()


def items_of(project):
    """PROJECT.md's items by ID in file order, and the problems with their markers.
    Implements PRC-10, see A15.12 step 7."""
    gone = retired(project)
    items, problems, current = {}, [], None
    for i, line in enumerate(without_examples(project)):
        if line.startswith("#"):
            current = None
            continue
        like = next((m for m in (p.match(line) for p in MARKER_LIKE) if m), None)
        if not like:
            if current:
                current.end = i
            continue
        m = MARKER.match(line)
        if not m:
            token = like.group(1)
            what = "is not an ID (three capitals, a dash, 2 or 3 digits)" if not re.fullmatch(ID, token) else \
                "has a marker that does not read as `ID` **Name** *(Status)*"
            problems.append(f"PROJECT.md line {i + 1}: `{token}` {what}")
            current = None
            continue
        id_, name, status = m.groups()
        if status not in STATUSES:
            problems.append(f"PROJECT.md line {i + 1}: `{id_}` has the status *{status}*, not one of {', '.join(STATUSES)}")
        if id_ in gone:
            problems.append(f"PROJECT.md line {i + 1}: `{id_}` is retired and may not be used again")
            current = None
            continue
        if id_ in items:
            problems.append(f"PROJECT.md line {i + 1}: `{id_}` is defined twice (first on line {items[id_].start + 1})")
            current = None
            continue
        current = items[id_] = Item(id_, name, status, i)
    return items, problems


def citations(text, areas):
    """(line from 1, ID) for each ID a text cites: anything shaped like an ID inside backticks, and outside them only
    IDs of a known area, so `SHA-256` in prose is never taken for one."""
    out = []
    for n, line in enumerate(text.split("\n"), 1):
        for span in BACKTICKED.findall(line):
            out += [(n, x) for x in ID_RE.findall(span)]
        out += [(n, x) for x in ID_RE.findall(BACKTICKED.sub(" ", line)) if x[:3] in areas]
    return out


def anchor(heading):
    """A heading's link anchor as the Markdown viewers make it."""
    return re.sub(r"[^\w\- ]", "", heading.lower()).replace(" ", "-")


def generated_lists(project, items):
    """What each generated list of PROJECT.md must hold: the contents exactly; the open items and the proposals by
    their IDs, in file order (their words are the writer's)."""
    lines = []
    for h in re.findall(r"^## (.+)$", project, re.M):
        if h == "Contents":
            continue
        m = re.fullmatch(r"(\d+)\. (.+)", h)
        # One sentence a line, as the whole file is written: "1." ends a line of its own.
        text = f"{m.group(1)}.\n  {m.group(2)}" if m else h
        lines.append(f"- [{text}](#{anchor(h)})")
    return {
        "contents": "\n".join(lines) + "\n",
        "open items": [i.id for i in items.values() if i.status == "To test"],
        "proposals": [i.id for i in items.values() if i.status == "Proposed"],
    }


def check_project(project):
    """The file check on PROJECT.md: its markers, citations and generated lists. Returns (items, problems, count)."""
    items, problems = items_of(project)
    gone = retired(project)
    areas = {i[:3] for i in items}
    # A marker's own ID defines its item rather than citing it, even when the marker is malformed.
    lines = [BACKTICKED.sub(" ", line, count=1) if any(p.match(line) for p in MARKER_LIKE) else line
             for line in without_examples(project)]
    cited = citations("\n".join(lines), areas)
    for n, x in cited:
        if x in gone and x not in items:
            problems.append(f"PROJECT.md line {n}: cites the retired `{x}`")
        elif x not in items:
            problems.append(f"PROJECT.md line {n}: `{x}` is not defined")
    want = generated_lists(project, items)
    found = {name: body for name, body in GENERATED.findall(project)}
    for name in ("contents", "open items", "proposals"):
        if name not in found:
            problems.append(f"PROJECT.md: no generated list '{name}'")
            continue
        body = found[name]
        if name == "contents":
            ok = body == want[name]
        else:
            listed = ID_RE.findall(body)
            ok = listed == want[name] and (listed or body.strip() == "- None at present.")
        if not ok:
            problems.append(f"PROJECT.md: the generated list '{name}' is not current")
    return items, problems, len(cited)


# ARCHITECTURE.md and IMPLEMENTATION.md.

def check_citations(name, text, items, gone, sections):
    """Every ID a document cites is a live item, and every section it cites is a heading of ARCHITECTURE.md."""
    problems, count = [], 0
    areas = {i[:3] for i in items} | {i[:3] for i in gone}
    for n, x in citations(text, areas):
        count += 1
        if x in gone:
            problems.append(f"{name} line {n}: cites the retired `{x}`")
        elif x not in items:
            problems.append(f"{name} line {n}: `{x}` is not defined in PROJECT.md")
    for n, line in enumerate(text.split("\n"), 1):
        if name == "ARCHITECTURE.md" and line.startswith("#"):
            continue  # a heading defines its section
        for s in SECTION.findall(line):
            count += 1
            if s not in sections:
                problems.append(f"{name} line {n}: section {s} is not a heading of ARCHITECTURE.md")
    return problems, count


def alpha_sections(plan):
    """(alpha such as `00b`, heading line from 1, the section's lines) for each `### α..` section of the plan."""
    lines = plan.split("\n")
    out = []
    for i, line in enumerate(lines):
        m = ALPHA_HEADING.match(line)
        if m:
            j = i + 1
            while j < len(lines) and not re.match(r"^#{1,3} ", lines[j]):
                j += 1
            out.append((m.group(1), i + 1, lines[i + 1:j]))
    return out


def field(lines, label):
    """The text of an alpha's field: from its label to the next label."""
    out, inside = [], False
    for line in lines:
        f = FIELD.match(line)
        if f:
            inside = f.group(1) == label
        if inside:
            out.append(line)
    return "\n".join(out)


def check_plan(plan):
    """Each alpha section holds the eleven fields in order, and its task lines carry unique IDs of its alpha."""
    problems, seen = [], {}
    for alpha, line, body in alpha_sections(plan):
        labels = [f.group(1) for f in map(FIELD.match, body) if f and f.group(1) in FIELDS]
        if labels != FIELDS:
            problems.append(f"IMPLEMENTATION.md line {line}: α{alpha}'s fields are {labels}, not the eleven in order")
        in_tasks = False
        for k, text in enumerate(body, line + 1):
            f = FIELD.match(text)
            if f:
                in_tasks = f.group(1) == "Tasks"
            t = TASK.match(text)
            if in_tasks and re.match(r"^\d+\.\s", text) and not t:
                problems.append(f"IMPLEMENTATION.md line {k}: a numbered line of α{alpha}'s tasks has no task ID")
            if not t:
                continue
            task = t.group(1)
            if not re.fullmatch(rf"T{alpha}\.\d+", task):
                problems.append(f"IMPLEMENTATION.md line {k}: task `{task}` is not one of α{alpha}'s (T{alpha}.<n>)")
            if task in seen:
                problems.append(f"IMPLEMENTATION.md line {k}: task `{task}` repeats line {seen[task]}")
            seen.setdefault(task, k)
    return problems


# The commit check (PRC-07).

def changed_ids(old, new):
    """The IDs whose item lines differ between two versions of PROJECT.md."""
    old_items, _ = items_of(old)
    new_items, _ = items_of(new)

    def owner(items, line):
        return next((i.id for i in items.values() if i.start <= line <= i.end), None)

    ids = set()
    a, b = old.split("\n"), new.split("\n")
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(None, a, b, autojunk=False).get_opcodes():
        if tag != "equal":
            ids.update(owner(old_items, i) for i in range(i1, i2))
            ids.update(owner(new_items, j) for j in range(j1, j2))
    ids.discard(None)
    return ids


CHANGED = re.compile(rf"^Changed:\s*(?P<ids>{ID}(?:,\s*{ID})*)\s*\((?P<why>.*)\)$", re.S)


def changed_entries(message):
    """A commit message's `Changed:` entries, each with the lines its brackets run onto, joined by spaces."""
    entries, current = [], None
    for line in message.split("\n"):
        if line.strip().startswith("Changed:"):
            current = [line.strip()]
            entries.append(current)
        elif current is not None and " ".join(current).count("(") > " ".join(current).count(")"):
            current.append(line.strip())
        else:
            current = None
    return [" ".join(e) for e in entries]


def item_words(project, item):
    """An item's text with its spacing evened, so a blank line or a rewrapped sentence changes no words."""
    return " ".join(" ".join(project.split("\n")[item.start:item.end + 1]).split())


def needs_owner(old, new):
    """The IDs whose words a change makes or changes while Decided, or takes from Decided (PRC-07)."""
    old_items, _ = items_of(old)
    new_items, _ = items_of(new)
    out = set()
    for id_ in set(old_items) | set(new_items):
        a, b = old_items.get(id_), new_items.get(id_)
        if "Decided" not in (a and a.status, b and b.status):
            continue
        if a is None or b is None or item_words(old, a) != item_words(new, b):
            out.add(id_)
    return out


def check_commit(sha, message, old, new):
    """A commit changing PROJECT.md names every ID whose lines it changed on its `Changed:` lines, each with its
    reason in brackets, and the owner's OK for every item it makes Decided or changes while Decided (PRC-07).
    Implements PRC-07, see A15.12 step 7."""
    entries = changed_entries(message)
    if not entries:
        return [f"commit {sha[:12]} changes PROJECT.md with no `Changed:` line (PRC-07)"]
    problems, named, approved, unreasoned = [], set(), set(), set()
    for e in entries:
        ids = set(ID_RE.findall(e))
        named |= ids
        m = CHANGED.match(e)
        if not m or not ID_RE.sub("", m.group("why")).strip(" ,;:"):
            unreasoned |= ids
            problems.append(f"commit {sha[:12]}: `{e[:60]}` gives no reason in brackets after its IDs (PRC-07)")
        elif "owner OK" in m.group("why"):
            approved |= set(ID_RE.findall(m.group("ids")))
    missing = sorted(changed_ids(old, new) - named)
    if missing:
        problems.append(f"commit {sha[:12]} changes {', '.join(missing)} in PROJECT.md without naming them on "
                        "`Changed:`")
    # An ID left unnamed, or named without a reason, has failed already.
    unapproved = sorted((needs_owner(old, new) & named) - approved - unreasoned)
    if unapproved:
        problems.append(f"commit {sha[:12]} makes or changes {', '.join(unapproved)} as Decided with no `owner OK` "
                        "in its reason (PRC-07)")
    return problems


def file_check(project, arch, plan, commits):
    """The whole file check: (problems, item count, citation count). `commits` holds (sha, message, PROJECT.md
    before, PROJECT.md after) for each commit to check."""
    items, problems, count = check_project(project)
    gone = retired(project)
    sections = set(ARCH_HEADING.findall(arch))
    for name, text in (("ARCHITECTURE.md", arch), ("IMPLEMENTATION.md", plan)):
        p, c = check_citations(name, text, items, gone, sections)
        problems += p
        count += c
    problems += check_plan(plan)
    for sha, message, old, new in commits:
        problems += check_commit(sha, message, old, new)
    return problems, len(items), count


# The coverage check (PRC-12, A15.12 step 8).

SLASH = (".rs", ".js", ".mjs", ".kt")
HASH = (".sh", ".py")
SCANNED = ("crates", "tools", "web", "android", "tests", "data", "scenes")
SKIPPED = {"target", "build", "node_modules", "pkg", ".gradle", "__pycache__"}
CHECKS_SETTING = re.compile(r"^\s*checks\s*=\s*\[([^\]]*)\]")


def kinds_of(project, items):
    """Each item's kind (Feature, Rule or Context) from `### Kinds of item`: the area defaults and the exceptions;
    an area no line names holds features."""
    areas, exceptions = {}, {}
    m = re.search(r"^### Kinds of item\n(.*?)(?=^#)", project, re.M | re.S)
    for line in (m.group(1) if m else "").split("\n"):
        k = re.match(r"^- \*\*(Context|Rules|Features):\*\*", line)
        if k:
            kind = {"Context": "Context", "Rules": "Rule", "Features": "Feature"}[k.group(1)]
            for token in BACKTICKED.findall(line):
                if re.fullmatch(ID, token):
                    exceptions[token] = kind
                elif re.fullmatch(r"[A-Z]{3}", token):
                    areas[token] = kind
    return {i: exceptions.get(i, areas.get(i[:3], "Feature")) for i in items}


def id_lines(path, text):
    """(line from 1, kind, IDs) for each line naming IDs: `// checks:` and `# checks:` lines, `Implements` doc
    lines, and a catalogue entry's or scene's `checks = [..]`."""
    out = []
    slash, hashed = path.endswith(SLASH), path.endswith(HASH)
    setting = path.startswith(("data/", "scenes/"))
    for n, line in enumerate(text.split("\n"), 1):
        s = line.strip()
        if (slash and s.startswith("// checks:")) or (hashed and s.startswith("# checks:")):
            out.append((n, "checks", ID_RE.findall(s)))
        elif slash and s.startswith(("///", "//!")) and "mplements" in s:
            out.append((n, "implements", ID_RE.findall(s)))
        elif setting and CHECKS_SETTING.match(line):
            out.append((n, "checks", ID_RE.findall(CHECKS_SETTING.match(line).group(1))))
    return out


def section_of(plan, heading):
    m = re.search(r"^" + re.escape(heading) + r"\n(.*?)(?=^## |\Z)", plan, re.M | re.S)
    return m.group(1) if m else ""


def tasks_of(plan):
    """(task ID, line from 1, text) for each task: its numbered line up to the next task, field or heading."""
    out, current = [], None
    for n, line in enumerate(plan.split("\n"), 1):
        t = TASK.match(line)
        if t and re.fullmatch(r"T\d{2}[a-e]?\.\d+", t.group(1)):
            current = [t.group(1), n, [line]]
            out.append(current)
        elif current and (FIELD.match(line) or line.startswith("#")):
            current = None
        elif current:
            current[2].append(line)
    return [(t, n, "\n".join(lines)) for t, n, lines in out]


def serves(plan):
    """{ID: [alphas]} from every alpha's Serves line, in plan order."""
    out = {}
    for alpha, _, body in alpha_sections(plan):
        for x in ID_RE.findall(field(body, "Serves")):
            out.setdefault(x, [])
            if alpha not in out[x]:
                out[x].append(alpha)
    return out


def coverage(files):
    """The coverage check over a repository given as {path: text}: (problems, a summary).
    Implements PRC-12, see A15.12 step 8."""
    project, plan = files["PROJECT.md"], files["IMPLEMENTATION.md"]
    items, _ = items_of(project)
    gone, kinds = retired(project), kinds_of(project, items)
    problems, tested, implemented, named, tests = [], set(), set(), 0, 0
    for path in sorted(p for p in files if p not in DOCUMENTS):
        text = files[path]
        # Every ID named in code, tests, catalogues and scenes is a live item.
        for n, kind, ids in id_lines(path, text):
            if kind == "checks" and not ids:
                problems.append(f"{path}:{n}: a checks line names no ID")
            for x in ids:
                named += 1
                if x in gone:
                    problems.append(f"{path}:{n}: names the retired `{x}`")
                elif x not in items:
                    problems.append(f"{path}:{n}: `{x}` is not defined in PROJECT.md")
                else:
                    (tested if kind == "checks" else implemented).add(x)
        # Every Rust test names what it checks on a `// checks:` line among the four lines above it.
        if path.startswith("crates/") and path.endswith(".rs"):
            lines = text.split("\n")
            for i, line in enumerate(lines):
                if line.strip().startswith("#[test]"):
                    tests += 1
                    above = [x.strip() for x in lines[max(0, i - 4):i]]
                    if not any(x.startswith("// checks:") and ID_RE.search(x) for x in above):
                        problems.append(f"{path}:{i + 1}: a #[test] with no `// checks:` line in the four lines above")
    # Every task names an item.
    tasks = tasks_of(plan)
    for t, n, text in tasks:
        if not any(x in items for x in ID_RE.findall(text)):
            problems.append(f"IMPLEMENTATION.md line {n}: task {t} names no item of PROJECT.md")
    # Every live feature and rule is served by an alpha still in the plan, kept by every alpha, or built (named by
    # an `Implements` line), since the plan keeps no record of done alphas.
    kept = set(ID_RE.findall(section_of(plan, RULES_HEADING)))
    served = serves(plan)
    live = [i for i in items.values() if i.status != "Proposed" and kinds[i.id] in ("Feature", "Rule")]
    for it in live:
        if it.id not in served and it.id not in kept and it.id not in implemented:
            problems.append(f"`{it.id}` ({kinds[it.id].lower()}) is not mapped: no alpha's Serves line names it, "
                            f"nor {RULES_HEADING}, nor an Implements line")
    # Every ID code implements, the kept rules aside, is named by a test, a scene or a catalogue entry.
    for x in sorted(implemented - kept - tested):
        problems.append(f"`{x}` is implemented in code, but no test, scene or catalogue entry names it")
    new = with_map(files)
    if new is not None and new != plan:
        problems.append("IMPLEMENTATION.md: the coverage map is not current (python3 tools/filecheck.py map --write)")
    summary = (f"{named} IDs named in code and tests, {tests} Rust tests, {len(tasks)} tasks, "
               f"{len(live)} features and rules mapped, {len(implemented)} IDs implemented in code")
    return problems, summary


def coverage_map(files):
    """The coverage map's section, from its heading to the end of the plan."""
    project, plan = files["PROJECT.md"], files["IMPLEMENTATION.md"]
    items, _ = items_of(project)
    kinds = kinds_of(project, items)
    kept = set(ID_RE.findall(section_of(plan, RULES_HEADING)))
    served = serves(plan)
    implemented = {x for p, t in files.items() if p not in DOCUMENTS for _, k, ids in id_lines(p, t)
                   if k == "implements" for x in ids}
    lines = [MAP_HEADING, "", MAP_INTRO, ""]
    for it in items.values():
        if it.id in served:
            where = ", ".join("α" + a for a in served[it.id])
        elif it.id in kept:
            where = "every alpha"
        elif kinds[it.id] == "Context":
            where = "context"
        elif it.id in implemented:
            where = "built"
        else:
            where = "not mapped"
        lines.append(f"- `{it.id}` {it.name}: {where}")
    return "\n".join(lines) + "\n"


def with_map(files):
    """The plan with its coverage map made afresh, or None when it has no map."""
    plan = files["IMPLEMENTATION.md"]
    at = plan.find("\n" + MAP_HEADING + "\n")
    return None if at < 0 else plan[:at + 1] + coverage_map(files)


def repo_files(root=ROOT):
    """{path: text} for PROJECT.md, IMPLEMENTATION.md and every source the coverage check reads."""
    files = {p: read(os.path.join(root, p)) for p in ("PROJECT.md", "IMPLEMENTATION.md")}
    for top in SCANNED:
        for dirpath, dirnames, filenames in os.walk(os.path.join(root, top)):
            rel = os.path.relpath(dirpath, root).replace(os.sep, "/")
            dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED and f"{rel}/{d}" != "tools/tests/filecheck")
            for name in sorted(filenames):
                path = f"{rel}/{name}"
                setting = path.startswith(("data/", "scenes/")) and name.endswith((".md", ".toml"))
                if name.endswith(SLASH + HASH) or setting:
                    files[path] = read(os.path.join(root, path))
    return files


# The note (PRC-11) and the gate (A15.13 step 6).

def check_note(text):
    """Problems with an alpha's note: its five headings, and a link to the APK."""
    headings = {m.strip() for m in re.findall(r"^#{1,6}\s+(.+)$", text, re.M)}
    problems = [f"no heading '{h}'" for h in NOTE_HEADINGS if h not in headings]
    if not re.search(r"https?://\S+/dist/kindling\.apk\b", text):
        problems.append("no link to dist/kindling.apk")
    return problems


ALPHA = re.compile(r"α(\d{2})([a-e]?)")
STATUS_ROW = re.compile(r"^\|\s*α(\d{2})([a-e]?)\s*\|", re.M)
SESSION = re.compile(r"session_[A-Za-z0-9]+")
SUBAGENT = re.compile(r"subagent:[a-z0-9][a-z0-9-]*")


def ends_its_number(alpha, plan):
    """Whether an alpha (`α02c`) ends its number: no row of the plan's status table has its number and a later
    letter. Its own row has already left the plan when the gate runs."""
    m = ALPHA.fullmatch(alpha)
    return not any(n == m.group(1) and s > m.group(2) for n, s in STATUS_ROW.findall(plan))


def gate(description, head, only_results, head_passed, parent_passed, sessions, plan):
    """Problems with merging a pull request (A15.13 step 6): the approved commit is the head, its checks passed
    (or its parent's, the head adding only results/), and the reviewer is the builder for an alpha a later letter of
    its number follows, else a subagent or a session that built none of the branch.
    Implements PRC-09, see A15.13."""
    m = re.search(r"^\s*`?Review: APPROVE\s+([0-9a-f]{7,40})\s+([^\s`]+)", description, re.M)
    if not m:
        return ["no 'Review: APPROVE <commit> <reviewer>' line"]
    commit, reviewer = m.groups()
    problems = []
    if len(commit) < 12 or not head.startswith(commit[:12]):
        problems.append(f"the approved commit {commit} is not the head {head[:12]}")
    if not (head_passed or (only_results and parent_passed)):
        problems.append(f"no passing results/checks for {head[:12]}, nor for its parent with a head adding only results/")
    a = ALPHA.search(description.strip().split("\n", 1)[0])
    if not a:
        return problems + ["the description does not open with the alpha's name (as α02c)"]
    alpha = a.group(0)
    last = ends_its_number(alpha, plan)
    if reviewer == "builder":
        if last:
            problems.append(f"{alpha} ends its number, so a subagent or another session reviews it, not the builder")
        return problems
    if not SESSION.search(reviewer) and not SUBAGENT.fullmatch(reviewer):
        problems.append(f"the reviewer {reviewer} is not the builder, a subagent or a session")
    if not last:
        problems.append(f"{alpha} does not end its number, so its builder reviews it (PRC-09)")
    if set(SESSION.findall(reviewer)) & {s for t in sessions for s in SESSION.findall(t)}:
        problems.append(f"the reviewer's session {reviewer} also built this branch")
    return problems


# The self-test: one planted fault per message, each failing with it alone, and the clean fixture passing.

def fixture(case_dir):
    out = {}
    for dirpath, _, names in os.walk(case_dir):
        for name in names:
            full = os.path.join(dirpath, name)
            out[os.path.relpath(full, case_dir).replace(os.sep, "/")] = read(full)
    return out


def edit(text, old, new):
    assert old in text, f"planted fault: {old!r} not in the fixture"
    return text.replace(old, new, 1)


# (name, the fault: {path: (old, new)}, a "commit" message, or "stale map", the message it must give alone). The
# builder regenerates the map after any change, so every case but "stale map" runs on a map made afresh.
EXTRA = "- `CTX-01` **Background** *(Decided)*: Context only."
PLANTED = [
    ("not an ID", {"PROJECT.md": (EXTRA, EXTRA + "\n- `CTX1` **Extra** *(Decided)*: x.")}, "is not an ID"),
    ("marker", {"PROJECT.md": (EXTRA, EXTRA + "\n- `CTX-05` Extra *(Decided)*: x.")}, "does not read as"),
    ("status", {"PROJECT.md": (EXTRA, EXTRA + "\n- `CTX-05` **Extra** *(Maybe)*: x.")}, "has the status *Maybe*"),
    ("retired reused", {"PROJECT.md": (EXTRA, EXTRA + "\n- `CTX-09` **Extra** *(Decided)*: x.")},
     "may not be used again"),
    ("twice", {"PROJECT.md": (EXTRA, EXTRA + "\n- `CTX-01` **Again** *(Decided)*: x.")}, "is defined twice"),
    ("undefined in PROJECT.md", {"PROJECT.md": ("follows `ONE-01`.", "follows `ONE-07`.")}, "`ONE-07` is not defined"),
    ("retired cited", {"ARCHITECTURE.md": ("Serves `ONE-01`.", "Serves `ONE-09`.")}, "cites the retired `ONE-09`"),
    ("section", {"IMPLEMENTATION.md": ("**Architecture:** `A1.1`.", "**Architecture:** `A1.4`.")},
     "section A1.4 is not a heading"),
    ("fields", {"IMPLEMENTATION.md": ("**Data:** none.\n", "")}, "not the eleven in order"),
    ("task alpha", {"IMPLEMENTATION.md": ("1. `T01.1`", "1. `T02.1`")}, "is not one of α01's"),
    ("task twice", {"IMPLEMENTATION.md": ("2. `T01.2`", "2. `T01.1`")}, "repeats line"),
    ("task without ID", {"IMPLEMENTATION.md": ("2. `T01.2` **Second", "2. **Second")}, "has no task ID"),
    ("contents", {"PROJECT.md": ("- [1.\n  One](#1-one)", "- [1. One](#1-one)")}, "'contents' is not current"),
    ("open items", {"PROJECT.md": ("- **Third** (`ONE-03`): measured later.", "- None at present.")},
     "'open items' is not current"),
    ("proposals", {"PROJECT.md": ("**Second** *(Decided)*", "**Second** *(Proposed)*")}, "'proposals' is not current"),
    ("no Changed line", {"PROJECT.md": ("Its words.", "Its new words."), "commit": "Edit\n"},
     "with no `Changed:` line"),
    ("Changed misses one", {"PROJECT.md": ("Its words.", "Its new words."), "commit": "Edit\n\nChanged: ONE-01 (x)\n"},
     "changes ONE-02 in PROJECT.md without naming"),
    ("Changed without reason", {"PROJECT.md": ("Its words.", "Its new words."), "commit": "Edit\n\nChanged: ONE-02\n"},
     "gives no reason in brackets"),
    ("Decided without OK", {"PROJECT.md": ("Its words.", "Its new words."),
                            "commit": "Edit\n\nChanged: ONE-02 (new words)\n"}, "with no `owner OK`"),
    ("code names undefined", {"crates/kd-one/src/lib.rs": ("// checks: ONE-01", "// checks: ONE-08")},
     "`ONE-08` is not defined in PROJECT.md"),
    ("code names retired", {"crates/kd-one/src/lib.rs": ("// checks: ONE-01", "// checks: ONE-01 ONE-09")},
     "names the retired `ONE-09`"),
    ("empty checks", {"tools/tests/test_one.py": ("# checks: ONE-01", "# checks:")}, "a checks line names no ID"),
    ("test without checks", {"crates/kd-one/src/lib.rs": ("    // checks: ONE-01\n", "")},
     "no `// checks:` line"),
    ("task without item", {"IMPLEMENTATION.md": ("(`ONE-02`, A1.1)", "(A1.1)")}, "task T01.2 names no item"),
    ("not mapped", {"IMPLEMENTATION.md": ("**Serves:** `ONE-01`, `ONE-02`, `ONE-03`.", "**Serves:** `ONE-01`, `ONE-03`.")},
     "`ONE-02` (feature) is not mapped"),
    ("implemented untested", {"crates/kd-one/src/lib.rs": ("/// Implements ONE-01", "/// Implements ONE-01 ONE-03")},
     "`ONE-03` is implemented in code, but no test"),
    ("stale map", {"IMPLEMENTATION.md": ("- `ONE-02` Second: α01", "- `ONE-02` Second: built"), "stale map": True},
     "the coverage map is not current"),
]


def run_case(clean, faults):
    files = dict(clean)
    commits = []
    for path, change in faults.items():
        if path not in ("commit", "stale map"):
            files[path] = edit(files[path], *change)
    if "stale map" not in faults:
        files["IMPLEMENTATION.md"] = with_map(files) or files["IMPLEMENTATION.md"]
    if "commit" in faults:
        commits = [("0" * 40, faults["commit"], clean["PROJECT.md"], files["PROJECT.md"])]
    problems, _, _ = file_check(files["PROJECT.md"], files["ARCHITECTURE.md"], files["IMPLEMENTATION.md"], commits)
    return problems + coverage(files)[0]


def selftest():
    """Prints a line a case and the verdict; returns the exit code.
    Implements PRC-12, see A15.12 step 8."""
    clean = fixture(os.path.join(FIXTURES, "clean"))
    bad = run_case(clean, {})
    print(("ok   " if not bad else "FAIL ") + "the clean fixture passes" + "".join(f"\n       {p}" for p in bad))
    failures = bool(bad)
    for name, faults, expect in PLANTED:
        problems = run_case(clean, faults)
        good = len(problems) == 1 and expect in problems[0]
        failures += not good
        print(("ok   " if good else "FAIL ") + f"{name}: " + ("; ".join(problems) or f"passed, but must fail: {expect}"))
    print(f"Selftest: OK ({len(PLANTED)} planted faults each fail alone, the clean fixture passes)" if not failures
          else f"Selftest: FAIL ({failures})")
    return 0 if not failures else 1


# Running.

def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def git(*args):
    return subprocess.run(["git", "-C", ROOT, *args], check=True, capture_output=True, text=True).stdout


def show(rev, path):
    r = subprocess.run(["git", "-C", ROOT, "show", f"{rev}:{path}"], capture_output=True, text=True)
    return r.stdout if r.returncode == 0 else ""


def commits_changing(path):
    """(sha, message, before, after) for each commit since main, merges aside, that changes a file."""
    shas = git("log", "--no-merges", "--format=%H", "origin/main..HEAD", "--", path).split()
    return [(s, git("log", "-1", "--format=%B", s), show(f"{s}^", path), show(s, path)) for s in shas]


def known_findings():
    """Findings awaiting the owner: `<finding> | <date> | awaiting owner OK` a line, `#` a comment."""
    path = os.path.join(ROOT, KNOWN)
    if not os.path.exists(path):
        return set()
    lines = (line.strip() for line in read(path).split("\n"))
    return {line.split(" | ")[0].strip() for line in lines if line and not line.startswith("#")}


def report(prefix, problems, ok_line):
    known = known_findings()
    left = [p for p in problems if p not in known]
    for p in sorted(known & set(problems)):
        print(f"{prefix}: known, awaiting the owner: {p}")
    for p in left:
        print(f"{prefix}: {p}")
    print(ok_line if not left else f"{prefix}: FAIL ({len(left)} problems)")
    return 0 if not left else 1


def passed(commit12):
    path = os.path.join(ROOT, "results", "checks", f"{commit12}.json")
    if not os.path.exists(path):
        return False
    r = json.loads(read(path))
    return r.get("result") == "PASS" and r.get("commit") == commit12


def main(argv):
    if argv == ["file"]:
        try:
            git("rev-parse", "--verify", "-q", "origin/main")
        except subprocess.CalledProcessError:
            print("File check: fetch main first: git fetch origin +refs/heads/main:refs/remotes/origin/main")
            return 1
        commits = commits_changing("PROJECT.md")
        docs = [read(os.path.join(ROOT, d)) for d in DOCUMENTS]
        problems, n, m = file_check(*docs, commits)
        return report("File check", problems,
                      f"File check: OK ({n} items, {m} citations, {len(commits)} commits changing PROJECT.md)")
    if argv == ["ids", "--merge"]:
        problems, summary = coverage(repo_files())
        return report("Coverage", problems, f"Coverage: OK ({summary})")
    if argv in (["map"], ["map", "--write"]):
        files = repo_files()
        new = with_map(files)
        if new is None:
            print(f"Map: IMPLEMENTATION.md has no '{MAP_HEADING}' section")
            return 1
        if argv[1:] == ["--write"]:
            with open(os.path.join(ROOT, "IMPLEMENTATION.md"), "w", encoding="utf-8") as f:
                f.write(new)
            print("Map: written")
        else:
            print(coverage_map(files), end="")
        return 0
    if argv == ["note"]:
        path = os.path.join(ROOT, "dist", "NOTE.md")
        problems = check_note(read(path)) if os.path.exists(path) else ["dist/NOTE.md is missing"]
        for p in problems:
            print(f"Note: {p}")
        print("Note: OK" if not problems else "Note: FAIL")
        return 0 if not problems else 1
    if argv == ["selftest"]:
        return selftest()
    if len(argv) == 2 and argv[0] == "gate":
        description = read(argv[1])
        try:  # a pull request as the API gives it, or its description alone
            description = json.loads(description)["body"]
        except (ValueError, KeyError, TypeError):
            pass
        head, parent = git("rev-parse", "HEAD").strip(), git("rev-parse", "HEAD^").strip()
        changed = [f for f in git("diff", "--name-only", "HEAD^", "HEAD").split("\n") if f]
        only_results = bool(changed) and all(f.startswith("results/") for f in changed)
        trailers = git("log", "--format=%(trailers:key=Claude-Session,valueonly)", "origin/main..HEAD").split("\n")
        problems = gate(description, head, only_results, passed(head[:12]), passed(parent[:12]),
                        [t for t in trailers if t.strip()], read(os.path.join(ROOT, "IMPLEMENTATION.md")))
        for p in problems:
            print(f"Gate: {p}")
        print(f"Gate: PASS {head[:12]}" if not problems else "Gate: FAIL")
        return 0 if not problems else 1
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
