// B73 writer AI: the phone side (PRE-37, PRE-17, PRE-41, PRE-19; RSK-17, RSK-22).
//
// Runs Kindling's 20 sample prompts (10 hand-made records x 2 voices) through Gemini Nano, the phone's
// built-in model, using ML Kit's GenAI Prompt API. The model runs in Android's AICore service, outside the app.
// Per prompt it reports the time to the first word, words per second, the text and any error. It also reports
// whether the model was available or still downloading, the model's name, and heat and free memory before and
// after. The texts come back in the result so the cloud can run the fact checker on them (checker.py).
//
// Self-contained: one file, prompts embedded (generated by make_prompts.py; don't edit them here).
// Gradle, app module:  implementation("com.google.mlkit:genai-prompt:1.0.0-beta4")   (needs android.useAndroidX=true)
// Call WriterTest.run(context) from a worker thread, with the app in the foreground and the screen on:
// ML Kit refuses to generate for apps in the background. It stops by itself at the time budget (default 4.5 min).
package dev.kindling.pretests

import android.app.ActivityManager
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.BatteryManager
import android.os.Build
import android.os.PowerManager
import android.os.SystemClock
import com.google.mlkit.genai.common.DownloadStatus
import com.google.mlkit.genai.common.FeatureStatus
import com.google.mlkit.genai.common.GenAiException
import com.google.mlkit.genai.common.StreamingCallback
import com.google.mlkit.genai.prompt.Candidate
import com.google.mlkit.genai.prompt.Generation
import com.google.mlkit.genai.prompt.GenerativeModel
import com.google.mlkit.genai.prompt.ModelPreference
import com.google.mlkit.genai.prompt.ModelReleaseStage
import com.google.mlkit.genai.prompt.TextPart
import com.google.mlkit.genai.prompt.generateContentRequest
import com.google.mlkit.genai.prompt.generationConfig
import com.google.mlkit.genai.prompt.modelConfig
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeoutOrNull
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.atomic.AtomicLong

object WriterTest {
    const val VERSION = "b73-r1"

    class Prompt(val id: String, val rec: String, val voice: String, val dark: Boolean, val text: String)

    /** Blocking: call from a worker thread. Returns the result as JSON (about 15 KB with the 20 texts). */
    @JvmStatic
    @JvmOverloads
    fun run(context: Context, budgetMs: Long = 270_000L): JSONObject =
        runBlocking { runAll(context.applicationContext, budgetMs) }

    private fun now() = SystemClock.elapsedRealtime()

    private suspend fun runAll(ctx: Context, budgetMs: Long): JSONObject {
        val t0 = now()
        val deadline = t0 + budgetMs
        val out = JSONObject().put("b73", VERSION).put("api", "mlkit genai-prompt 1.0.0-beta4")
            .put("device", deviceInfo(ctx)).put("before", vitals(ctx))
        val passes = JSONArray()
        out.put("passes", passes)
        // FULL is the main test. FAST (a lighter variant, if the phone has it) only uses time that is left over.
        passes.put(runPass(ctx, ModelPreference.FULL, "FULL", deadline, allowDownload = true))
        if (deadline - now() > 60_000) {
            passes.put(runPass(ctx, ModelPreference.FAST, "FAST", deadline, allowDownload = false))
        } else {
            passes.put(JSONObject().put("preference", "FAST").put("skipped", "no time left"))
        }
        return out.put("after", vitals(ctx)).put("wall_ms", now() - t0)
    }

    private suspend fun runPass(ctx: Context, pref: Int, name: String, deadline: Long, allowDownload: Boolean): JSONObject {
        val pass = JSONObject().put("preference", name)
        val model = try {
            Generation.getClient(generationConfig {
                modelConfig = modelConfig {
                    releaseStage = ModelReleaseStage.STABLE
                    preference = pref
                }
            })
        } catch (t: Throwable) {
            return pass.put("status", "client_error").put("error", t.toString().take(200))
        }
        try {
            var status = model.checkStatus()
            pass.put("status_at_start", statusName(status))
            if (status == FeatureStatus.DOWNLOADABLE && allowDownload) {
                pass.put("download", download(model, minOf(deadline, now() + 90_000)))
                status = model.checkStatus()
            }
            val waitUntil = minOf(deadline, now() + 60_000)
            while (status == FeatureStatus.DOWNLOADING && now() < waitUntil) {
                delay(5_000)
                status = model.checkStatus()
            }
            pass.put("status", statusName(status))
            if (status != FeatureStatus.AVAILABLE) return pass
            pass.put("base_model", runCatching { model.getBaseModelName() }.getOrElse { "error: $it".take(120) })
            pass.put("token_limit", runCatching { model.getTokenLimit() }.getOrElse { -1 })
            val w0 = now()
            val warm = runCatching { model.warmup() }
            pass.put("warmup_ms", now() - w0).put("warmup_ok", warm.isSuccess)
            val runs = JSONArray()
            pass.put("runs", runs)
            for (p in PROMPTS) {
                val left = deadline - now()
                if (left < 15_000) {
                    pass.put("stopped", "time budget")
                    break
                }
                val r = runOne(model, p, minOf(60_000L, left))
                r.put("battery_c", batteryTempC(ctx)).put("thermal", thermalStatus(ctx))
                runs.put(r)
                val code = r.optString("error_code")
                if (code in STOP_CODES) {
                    pass.put("stopped", code)
                    break
                }
            }
            pass.put("summary", summary(runs))
        } catch (t: Throwable) {
            pass.put("error", t.toString().take(200))
        } finally {
            runCatching { model.close() }
        }
        return pass
    }

    private val STOP_CODES = setOf("BACKGROUND_USE_BLOCKED", "PER_APP_BATTERY_USE_QUOTA_EXCEEDED", "NOT_AVAILABLE",
        "NEEDS_SYSTEM_UPDATE", "AICORE_INCOMPATIBLE", "NOT_SUPPORTED")

    private suspend fun download(model: GenerativeModel, until: Long): JSONObject {
        val d = JSONObject()
        val t0 = now()
        val finished = withTimeoutOrNull(maxOf(1L, until - now())) {
            model.download().collect { s ->
                when (s) {
                    is DownloadStatus.DownloadStarted -> d.put("bytes_to_download", s.bytesToDownload)
                    is DownloadStatus.DownloadProgress -> d.put("bytes_done", s.totalBytesDownloaded)
                    is DownloadStatus.DownloadCompleted -> d.put("completed", true)
                    is DownloadStatus.DownloadFailed ->
                        d.put("failed", errorName(s.e.errorCode)).put("error", s.e.message?.take(200))
                }
            }
            true
        }
        return d.put("waited_ms", now() - t0).put("finished_waiting", finished == true)
    }

    private suspend fun runOne(model: GenerativeModel, p: Prompt, timeoutMs: Long): JSONObject {
        val r = JSONObject().put("id", p.id).put("voice", p.voice).put("dark", p.dark)
        val start = now()
        val first = AtomicLong(-1L)
        val streamed = StringBuffer()
        val request = generateContentRequest(TextPart(p.text)) {
            temperature = 0.3f
            topK = 20
            seed = 73
            candidateCount = 1
            maxOutputTokens = 256
        }
        val callback = object : StreamingCallback {
            override fun onNewText(text: String) {
                if (text.isNotBlank()) first.compareAndSet(-1L, now())
                streamed.append(text)
            }
        }
        try {
            val resp = withTimeoutOrNull(timeoutMs) { model.generateContent(request, callback) }
            val end = now()
            val cand = resp?.candidates?.firstOrNull()
            val text = (cand?.text ?: streamed.toString()).trim()
            val words = text.split(Regex("\\s+")).count { it.isNotEmpty() }
            val firstAt = if (first.get() > 0) first.get() else end
            r.put("ttfw_ms", firstAt - start).put("total_ms", end - start).put("words", words)
                .put("wps", if (end > firstAt) round2(words * 1000.0 / (end - firstAt)) else JSONObject.NULL)
                .put("wps_all", round2(words * 1000.0 / maxOf(1L, end - start)))
                .put("finish", finishName(cand?.finishReason)).put("text", text)
            if (resp == null) r.put("error_code", "TIMEOUT")
        } catch (e: GenAiException) {
            r.put("error_code", errorName(e.errorCode)).put("error", e.message?.take(200))
                .put("total_ms", now() - start).put("text", streamed.toString().trim())
        } catch (t: Throwable) {
            r.put("error_code", "EXCEPTION").put("error", t.toString().take(200)).put("total_ms", now() - start)
        }
        return r
    }

    private fun summary(runs: JSONArray): JSONObject {
        val ok = (0 until runs.length()).map { runs.getJSONObject(it) }.filter { !it.has("error_code") }
        fun median(xs: List<Double>) = if (xs.isEmpty()) JSONObject.NULL else xs.sorted()[xs.size / 2]
        return JSONObject().put("done", ok.size).put("tried", runs.length())
            .put("median_ttfw_ms", median(ok.map { it.optDouble("ttfw_ms") }))
            .put("median_wps", median(ok.mapNotNull { if (it.isNull("wps")) null else it.optDouble("wps") }))
            .put("max_total_ms", ok.maxOfOrNull { it.optLong("total_ms") } ?: JSONObject.NULL)
            .put("words", ok.sumOf { it.optInt("words") })
    }

    private fun round2(x: Double) = Math.round(x * 100) / 100.0

    private fun statusName(s: Int) = when (s) {
        FeatureStatus.AVAILABLE -> "available"
        FeatureStatus.DOWNLOADABLE -> "downloadable"
        FeatureStatus.DOWNLOADING -> "downloading"
        FeatureStatus.UNAVAILABLE -> "unavailable"
        else -> "unknown($s)"
    }

    private fun finishName(f: Int?) = when (f) {
        null -> "none"
        Candidate.FinishReason.STOP -> "stop"
        Candidate.FinishReason.MAX_TOKENS -> "max_tokens"
        else -> "other($f)"
    }

    private fun errorName(c: Int) = when (c) {
        GenAiException.ErrorCode.BUSY -> "BUSY"
        GenAiException.ErrorCode.CANCELLED -> "CANCELLED"
        GenAiException.ErrorCode.NOT_AVAILABLE -> "NOT_AVAILABLE"
        GenAiException.ErrorCode.REQUEST_TOO_LARGE -> "REQUEST_TOO_LARGE"
        GenAiException.ErrorCode.RESPONSE_GENERATION_ERROR -> "RESPONSE_GENERATION_ERROR"
        GenAiException.ErrorCode.RESPONSE_PROCESSING_ERROR -> "RESPONSE_PROCESSING_ERROR"
        GenAiException.ErrorCode.REQUEST_PROCESSING_ERROR -> "REQUEST_PROCESSING_ERROR"
        GenAiException.ErrorCode.NOT_SUPPORTED -> "NOT_SUPPORTED"
        GenAiException.ErrorCode.PER_APP_BATTERY_USE_QUOTA_EXCEEDED -> "PER_APP_BATTERY_USE_QUOTA_EXCEEDED"
        GenAiException.ErrorCode.BACKGROUND_USE_BLOCKED -> "BACKGROUND_USE_BLOCKED"
        GenAiException.ErrorCode.NOT_ENOUGH_DISK_SPACE -> "NOT_ENOUGH_DISK_SPACE"
        GenAiException.ErrorCode.NEEDS_SYSTEM_UPDATE -> "NEEDS_SYSTEM_UPDATE"
        GenAiException.ErrorCode.AICORE_INCOMPATIBLE -> "AICORE_INCOMPATIBLE"
        else -> "CODE_$c"
    }

    private fun deviceInfo(ctx: Context): JSONObject {
        fun version(pkg: String) = runCatching { ctx.packageManager.getPackageInfo(pkg, 0).versionName ?: "?" }
            .getOrElse { "not found" }
        return JSONObject().put("model", "${Build.MANUFACTURER} ${Build.MODEL}").put("soc", Build.SOC_MODEL)
            .put("android", Build.VERSION.RELEASE).put("sdk", Build.VERSION.SDK_INT)
            .put("security_patch", Build.VERSION.SECURITY_PATCH)
            .put("aicore", version("com.google.android.aicore"))
            .put("play_services", version("com.google.android.gms"))
            .put("private_compute_services", version("com.google.android.as.oss"))
    }

    private fun vitals(ctx: Context): JSONObject {
        val am = ctx.getSystemService(ActivityManager::class.java)
        val mi = ActivityManager.MemoryInfo().also { am?.getMemoryInfo(it) }
        val pm = ctx.getSystemService(PowerManager::class.java)
        return JSONObject().put("battery_c", batteryTempC(ctx)).put("thermal", thermalStatus(ctx))
            .put("headroom_10s", pm?.getThermalHeadroom(10)?.toDouble()?.let { if (it.isNaN()) null else round2(it) })
            .put("avail_mem_mb", mi.availMem / (1024 * 1024)).put("low_memory", mi.lowMemory)
    }

    private fun batteryTempC(ctx: Context): Double? {
        val i: Intent? = ctx.registerReceiver(null, IntentFilter(Intent.ACTION_BATTERY_CHANGED))
        val t = i?.getIntExtra(BatteryManager.EXTRA_TEMPERATURE, Int.MIN_VALUE) ?: Int.MIN_VALUE
        return if (t == Int.MIN_VALUE) null else t / 10.0
    }

    private fun thermalStatus(ctx: Context): Int = ctx.getSystemService(PowerManager::class.java)?.currentThermalStatus ?: -1

    // BEGIN GENERATED PROMPTS (make_prompts.py)
    val PROMPTS: List<Prompt> = listOf(
        Prompt("r01-doc", "r01", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: first discovery.
When: year 37, early winter, morning.
Place: Harum (their word; it means "cold hollow"), the winter camp of the Kesh band.
People:
- Imra: woman, 19 years old, of the Kesh band.
- Tavu: man, 23 years old, of the Kesh band; brother of Imra.
What happened, in order:
- Imra was shaping a scraper by striking cutting stone against a lump of heavy yellow stone.
- Sparks fell on dry moss beside her, and the moss began to smoke.
- Imra blew on the smoking moss, and it caught fire.
- She tried again 3 times that day, and the moss caught fire 2 of those times.
- Tavu saw it.
- Before this, the Kesh band kept fire only by carrying embers from camp to camp.
- This was the first time anyone in the world made fire by striking stones.
Beliefs (not facts):
- Imra believed (but was not sure): fire lives inside the heavy yellow stone.
Their own words for things (use these): "cutting stone", "heavy yellow stone".
"""),
        Prompt("r01-tra", "r01", "tradition", false, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: first discovery.
When: year 37, early winter, morning.
Place: Harum (their word; it means "cold hollow"), the winter camp of the Kesh band.
People:
- Imra: woman, 19 years old, of the Kesh band.
- Tavu: man, 23 years old, of the Kesh band; brother of Imra.
What happened, in order:
- Imra was shaping a scraper by striking cutting stone against a lump of heavy yellow stone.
- Sparks fell on dry moss beside her, and the moss began to smoke.
- Imra blew on the smoking moss, and it caught fire.
- She tried again 3 times that day, and the moss caught fire 2 of those times.
- Tavu saw it.
- Before this, the Kesh band kept fire only by carrying embers from camp to camp.
- This was the first time anyone in the world made fire by striking stones.
Beliefs (not facts):
- Imra believed (but was not sure): fire lives inside the heavy yellow stone.
Their own words for things (use these): "cutting stone", "heavy yellow stone".
"""),
        Prompt("r02-doc", "r02", "documentary", true, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: death from cold.
When: year 41, deep winter, night.
Place: Harum (their word; it means "cold hollow"), the old winter camp of the Kesh band.
Other place: Ulmeke (their word; it means "red cliff"), a camp 4 days' walk away.
People:
- Oru: man, 58 years old, of the Kesh band.
- Sefi: woman, 34 years old, of the Kesh band; daughter of Oru.
What happened, in order:
- In autumn, Oru broke his leg in a fall, and after that he could not walk far.
- Food ran out at Harum, so the Kesh band moved to Ulmeke, a walk of 4 days.
- The band left Oru behind at Harum with a small fire and 2 strips of dried meat.
- Sefi was the last to leave him.
- On his 4th night alone, the fire went out and Oru died of cold.
- 10 days later, 2 hunters of the band found his body beside the dead fire.
"""),
        Prompt("r02-tra", "r02", "tradition", true, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: death from cold.
When: year 41, deep winter, night.
Place: Harum (their word; it means "cold hollow"), the old winter camp of the Kesh band.
Other place: Ulmeke (their word; it means "red cliff"), a camp 4 days' walk away.
People:
- Oru: man, 58 years old, of the Kesh band.
- Sefi: woman, 34 years old, of the Kesh band; daughter of Oru.
What happened, in order:
- In autumn, Oru broke his leg in a fall, and after that he could not walk far.
- Food ran out at Harum, so the Kesh band moved to Ulmeke, a walk of 4 days.
- The band left Oru behind at Harum with a small fire and 2 strips of dried meat.
- Sefi was the last to leave him.
- On his 4th night alone, the fire went out and Oru died of cold.
- 10 days later, 2 hunters of the band found his body beside the dead fire.
"""),
        Prompt("r03-doc", "r03", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: birth.
When: year 52, spring, night.
Place: Sefa (their word; it means "wide water"), a lake; the Tulo band camped on its shore.
People:
- Kaya: woman, 22 years old, of the Tulo band.
- Anwe: woman, 44 years old, of the Tulo band; mother of Kaya.
- Lisu: woman, 30 years old, of the Tulo band.
What happened, in order:
- Kaya gave birth to a girl in the camp on the shore of Sefa.
- Anwe and Lisu helped her.
- The labour lasted most of the night.
- The girl was small, and she cried at once.
- She is the 2nd child of Kaya. The first, a boy, is 3 years old.
- The girl has no name yet.
Beliefs (not facts):
- the Tulo band believed (and was sure): a child is given a name only after it lives through its first winter.
"""),
        Prompt("r03-tra", "r03", "tradition", false, """Retell one event the way the storytellers of the Tulo band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Tulo band: they say "we" only for the Tulo band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: birth.
When: year 52, spring, night.
Place: Sefa (their word; it means "wide water"), a lake; the Tulo band camped on its shore.
People:
- Kaya: woman, 22 years old, of the Tulo band.
- Anwe: woman, 44 years old, of the Tulo band; mother of Kaya.
- Lisu: woman, 30 years old, of the Tulo band.
What happened, in order:
- Kaya gave birth to a girl in the camp on the shore of Sefa.
- Anwe and Lisu helped her.
- The labour lasted most of the night.
- The girl was small, and she cried at once.
- She is the 2nd child of Kaya. The first, a boy, is 3 years old.
- The girl has no name yet.
Beliefs (not facts):
- the Tulo band believed (and was sure): a child is given a name only after it lives through its first winter.
"""),
        Prompt("r04-doc", "r04", "documentary", true, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: feud killing.
When: year 63, late summer, dusk.
Place: Teshu (their word; it means "shallow crossing"), a ford of the river.
People:
- Anuk: man, 31 years old, of the Kesh band.
- Moro: man, 27 years old, of the Tulo band.
- Ishe: woman, 24 years old, of the Tulo band; sister of Moro.
- Pell: man, of the Kesh band; brother of Anuk, dead since spring.
What happened, in order:
- Anuk waited for Moro at Teshu.
- When Moro came to cross, Anuk killed him with a spear thrust to the belly. The spear had a cutting stone point.
- Moro died at the ford before dark.
- Ishe saw the killing from the far bank.
- Ishe ran to the Tulo camp and told them.
Beliefs (not facts):
- Anuk believed (and was sure): Moro killed his brother Pell in the spring. (This belief is why Anuk killed Moro.)
Known to the world but not to the people:
- In truth, Pell drowned in the river in the spring. No one killed him.
Their own words for things (use these): "cutting stone".
"""),
        Prompt("r04-tra", "r04", "tradition", true, """Retell one event the way the storytellers of the Tulo band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Tulo band: they say "we" only for the Tulo band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: feud killing.
When: year 63, late summer, dusk.
Place: Teshu (their word; it means "shallow crossing"), a ford of the river.
People:
- Anuk: man, 31 years old, of the Kesh band.
- Moro: man, 27 years old, of the Tulo band.
- Ishe: woman, 24 years old, of the Tulo band; sister of Moro.
- Pell: man, of the Kesh band; brother of Anuk, dead since spring.
What happened, in order:
- Anuk waited for Moro at Teshu.
- When Moro came to cross, Anuk killed him with a spear thrust to the belly. The spear had a cutting stone point.
- Moro died at the ford before dark.
- Ishe saw the killing from the far bank.
- Ishe ran to the Tulo camp and told them.
Beliefs (not facts):
- Anuk believed (and was sure): Moro killed his brother Pell in the spring. (This belief is why Anuk killed Moro.)
Their own words for things (use these): "cutting stone".
"""),
        Prompt("r05-doc", "r05", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: band split.
When: year 70, autumn.
Place: Ulmeke (their word; it means "red cliff"), a cliff with dry caves.
Other place: Kotara (their word; it means "salt shore"), the sea shore, 6 days' walk away.
People:
- Hesh: man, 40 years old, of the Amaru band.
- Nima: woman, 46 years old, of the Amaru band.
- Rafi: man, 17 years old, of the Amaru band; son of Hesh.
What happened, in order:
- The Amaru band, 26 people, argued for 2 days at Ulmeke about where to spend the winter.
- Hesh wanted to go to Kotara.
- Nima wanted to stay at Ulmeke.
- The band split: 11 people went with Hesh to Kotara, and 15 stayed with Nima at Ulmeke.
- Rafi, the son of Hesh, stayed with Nima.
Beliefs (not facts):
- Hesh believed (and was sure): the shellfish at Kotara do not run out in winter. (Why he wanted to go.)
- Nima believed (and was sure): the walk to Kotara is too long for the old and for small children. (Why she wanted to stay.)
"""),
        Prompt("r05-tra", "r05", "tradition", false, """Retell one event the way the storytellers of the Amaru band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Amaru band: they say "we" only for the Amaru band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: band split.
When: year 70, autumn.
Place: Ulmeke (their word; it means "red cliff"), a cliff with dry caves.
Other place: Kotara (their word; it means "salt shore"), the sea shore, 6 days' walk away.
People:
- Hesh: man, 40 years old, of the Amaru band.
- Nima: woman, 46 years old, of the Amaru band.
- Rafi: man, 17 years old, of the Amaru band; son of Hesh.
What happened, in order:
- The Amaru band, 26 people, argued for 2 days at Ulmeke about where to spend the winter.
- Hesh wanted to go to Kotara.
- Nima wanted to stay at Ulmeke.
- The band split: 11 people went with Hesh to Kotara, and 15 stayed with Nima at Ulmeke.
- Rafi, the son of Hesh, stayed with Nima.
Beliefs (not facts):
- Hesh believed (and was sure): the shellfish at Kotara do not run out in winter. (Why he wanted to go.)
- Nima believed (and was sure): the walk to Kotara is too long for the old and for small children. (Why she wanted to stay.)
"""),
        Prompt("r06-doc", "r06", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: dream that changed a mind.
When: year 77, late winter, night.
Place: Sefa (their word; it means "wide water"), a lake, frozen over.
People:
- Dabo: man, 26 years old, of the Kesh band.
- Ama: woman, of the Kesh band; mother of Dabo, dead.
- Pek: man, 29 years old, of the Kesh band.
- Hanu: man, 22 years old, of the Kesh band.
What happened, in order:
- Dabo planned to cross the frozen lake Sefa to hunt on the far shore. Crossing the ice saves a day of walking.
- The night before, Dabo dreamt that his dead mother Ama stood on the ice, and the ice broke under her.
- When he woke, Dabo changed his mind and did not cross the ice.
- He walked around the lake instead, which took him 2 days.
- That same morning, Pek and Hanu crossed the ice and came back safely.
Beliefs (not facts):
- Dabo believed (and was sure): the ice is strong enough to cross. (Before the dream.)
- Dabo believed (but was not sure): the ice will break. (After the dream.)
"""),
        Prompt("r06-tra", "r06", "tradition", false, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: dream that changed a mind.
When: year 77, late winter, night.
Place: Sefa (their word; it means "wide water"), a lake, frozen over.
People:
- Dabo: man, 26 years old, of the Kesh band.
- Ama: woman, of the Kesh band; mother of Dabo, dead.
- Pek: man, 29 years old, of the Kesh band.
- Hanu: man, 22 years old, of the Kesh band.
What happened, in order:
- Dabo planned to cross the frozen lake Sefa to hunt on the far shore. Crossing the ice saves a day of walking.
- The night before, Dabo dreamt that his dead mother Ama stood on the ice, and the ice broke under her.
- When he woke, Dabo changed his mind and did not cross the ice.
- He walked around the lake instead, which took him 2 days.
- That same morning, Pek and Hanu crossed the ice and came back safely.
Beliefs (not facts):
- Dabo believed (and was sure): the ice is strong enough to cross. (Before the dream.)
- Dabo believed (but was not sure): the ice will break. (After the dream.)
"""),
        Prompt("r07-doc", "r07", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: myth retold.
When: year 118, winter, night.
Place: Harum (their word; it means "cold hollow"), the winter camp of the Kesh band.
People:
- Shana: woman, 51 years old, of the Kesh band; teller.
What happened, in order:
- Shana told the story Tara-mi to 14 listeners at Harum.
The story: Tara-mi (it means "the coming of fire"), first told in year 45, by Imra.
- The old telling: Fire lived inside the heavy yellow stone. A woman named Imra struck the stone, and fire jumped into the moss.
- The telling now: The sky put fire inside the heavy yellow stone. The first mother struck the stone, and fire jumped into the dry grass.
- What changed: the sky was added, as the one who put fire in the stone; the name Imra was lost, and she became the first mother; the moss became dry grass.
Their own words for things (use these): "heavy yellow stone".
"""),
        Prompt("r07-tra", "r07", "tradition", false, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: myth retold.
When: year 118, winter, night.
Place: Harum (their word; it means "cold hollow"), the winter camp of the Kesh band.
People:
- Shana: woman, 51 years old, of the Kesh band; teller.
What happened, in order:
- Shana told the story Tara-mi to 14 listeners at Harum.
The story: Tara-mi (it means "the coming of fire"), first told in year 45, by Imra.
- The old telling: Fire lived inside the heavy yellow stone. A woman named Imra struck the stone, and fire jumped into the moss.
- The telling now: The sky put fire inside the heavy yellow stone. The first mother struck the stone, and fire jumped into the dry grass.
- What changed: the sky was added, as the one who put fire in the stone; the name Imra was lost, and she became the first mother; the moss became dry grass.
Their own words for things (use these): "heavy yellow stone".
"""),
        Prompt("r08-doc", "r08", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: sign.
When: year 90, summer, afternoon.
Place: Ulmeke (their word; it means "red cliff"), the camp of the Amaru band.
Other place: Sefa (their word; it means "wide water"), a lake.
People:
- Nima: woman, 66 years old, of the Amaru band.
What happened, in order:
- During a storm, sky-fire struck a lone tall tree on the ridge above the camp.
- The tree split and burned. No one was hurt.
- Nima said the sky-fire was a sign that the dead no longer wanted the band at Ulmeke.
- 17 of the 20 people of the Amaru band came to believe her.
- 3 days later, the band left Ulmeke and walked toward Sefa.
Beliefs (not facts):
- Nima believed (and was sure): the sky-fire was a sign that the dead no longer want the band at Ulmeke.
- 17 of the 20 people of the Amaru band believed (but was not sure): the same as Nima.
Their own words for things (use these): "sky-fire".
"""),
        Prompt("r08-tra", "r08", "tradition", false, """Retell one event the way the storytellers of the Amaru band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Amaru band: they say "we" only for the Amaru band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: sign.
When: year 90, summer, afternoon.
Place: Ulmeke (their word; it means "red cliff"), the camp of the Amaru band.
Other place: Sefa (their word; it means "wide water"), a lake.
People:
- Nima: woman, 66 years old, of the Amaru band.
What happened, in order:
- During a storm, sky-fire struck a lone tall tree on the ridge above the camp.
- The tree split and burned. No one was hurt.
- Nima said the sky-fire was a sign that the dead no longer wanted the band at Ulmeke.
- 17 of the 20 people of the Amaru band came to believe her.
- 3 days later, the band left Ulmeke and walked toward Sefa.
Beliefs (not facts):
- Nima believed (and was sure): the sky-fire was a sign that the dead no longer want the band at Ulmeke.
- 17 of the 20 people of the Amaru band believed (but was not sure): the same as Nima.
Their own words for things (use these): "sky-fire".
"""),
        Prompt("r09-doc", "r09", "documentary", true, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: raid and captives.
When: year 95, late autumn, before dawn.
Place: Sefa (their word; it means "wide water"), a lake; the Tulo band camped on its shore.
People:
- Kelo: man, 33 years old, of the Kesh band; led the raid.
- Gudo: man, 38 years old, of the Tulo band.
- Rena: woman, 17 years old, of the Tulo band.
- Oshi: woman, 15 years old, of the Tulo band.
Background:
- The Kesh band had killed little game that autumn.
What happened, in order:
- Before dawn, 7 men of the Kesh band, led by Kelo, attacked the Tulo camp at Sefa.
- They killed Gudo with clubs.
- They took Rena and Oshi captive and tied their hands with sinew cord.
- They made Rena and Oshi carry the dried meat of the Tulo band to the Kesh camp.
- The other Tulo people fled into the reeds.
Beliefs (not facts):
- Kelo believed (and was sure): the Tulo camp had more dried meat than it needed. (Why he led the raid.)
"""),
        Prompt("r09-tra", "r09", "tradition", true, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: raid and captives.
When: year 95, late autumn, before dawn.
Place: Sefa (their word; it means "wide water"), a lake; the Tulo band camped on its shore.
People:
- Kelo: man, 33 years old, of the Kesh band; led the raid.
- Gudo: man, 38 years old, of the Tulo band.
- Rena: woman, 17 years old, of the Tulo band.
- Oshi: woman, 15 years old, of the Tulo band.
Background:
- The Kesh band had killed little game that autumn.
What happened, in order:
- Before dawn, 7 men of the Kesh band, led by Kelo, attacked the Tulo camp at Sefa.
- They killed Gudo with clubs.
- They took Rena and Oshi captive and tied their hands with sinew cord.
- They made Rena and Oshi carry the dried meat of the Tulo band to the Kesh camp.
- The other Tulo people fled into the reeds.
Beliefs (not facts):
- Kelo believed (and was sure): the Tulo camp had more dried meat than it needed. (Why he led the raid.)
"""),
        Prompt("r10-doc", "r10", "documentary", false, """Write one entry for the chronicle of a band of early humans.

Voice: documentary. Calm, exact and plain, like a careful field report. Past tense, third person.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. You choose the words and the rhythm, never the content. Keep the people's own words for things exactly as the DATA writes them.
3. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
4. A belief is not a fact. Say who believed it, and say "believed", never "knew". Do not invent speech or quotes.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it, in active words. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write one paragraph of 60 to 110 words. Output only the entry. Never repeat these rules or the DATA's labels.

DATA:
Event: meeting and exchange.
When: year 102, spring, midday.
Place: Teshu (their word; it means "shallow crossing"), a ford of the river.
Other place: Kotara (their word; it means "salt shore"), the sea shore.
People:
- Temo: man, 35 years old, of the Kesh band.
- Yari: woman, 29 years old, of the Amaru band.
What happened, in order:
- The Kesh band and the Amaru band met by chance at Teshu.
- They had no words in common, so they pointed and laid things on the ground.
- Temo gave 3 lumps of red earth to Yari.
- Yari gave Temo a string of 12 white shells from Kotara.
- The two bands camped apart for 1 night and went their separate ways the next morning.
Their own words for things (use these): "red earth".
"""),
        Prompt("r10-tra", "r10", "tradition", false, """Retell one event the way the storytellers of the Kesh band tell it aloud, in their own tradition.

Voice: their own tradition. Spoken words, short sentences, simple words, some repetition. The tellers are the Kesh band: they say "we" only for the Kesh band, never for another band. Tell their beliefs the way they believe them.

Rules:
1. Use only the facts in the DATA below. Do not add any name, number, place, object, animal, weather, sound, feeling, cause, motive or image that is not in the DATA.
2. Add no spirits, gods, ancestors, omens or magic that the DATA does not have. Do not invent speech or quotes.
3. Keep the people's own words for things exactly as the DATA writes them.
4. Keep who did each thing exactly as the DATA says. Use a name, not "he" or "she", whenever two people could be meant.
5. If the DATA tells of killing, cruelty, death or captivity, say plainly what happened and who did it. Keep every forcing word ("made", "took captive", "left behind"). Do not soften it, hide it, hedge it, excuse it or judge it.
6. Write 60 to 110 words. Output only the telling. Never repeat these rules or the DATA's labels.

DATA:
Event: meeting and exchange.
When: year 102, spring, midday.
Place: Teshu (their word; it means "shallow crossing"), a ford of the river.
Other place: Kotara (their word; it means "salt shore"), the sea shore.
People:
- Temo: man, 35 years old, of the Kesh band.
- Yari: woman, 29 years old, of the Amaru band.
What happened, in order:
- The Kesh band and the Amaru band met by chance at Teshu.
- They had no words in common, so they pointed and laid things on the ground.
- Temo gave 3 lumps of red earth to Yari.
- Yari gave Temo a string of 12 white shells from Kotara.
- The two bands camped apart for 1 night and went their separate ways the next morning.
Their own words for things (use these): "red earth".
"""),
    )
    // END GENERATED PROMPTS
}
